# -*- coding: utf-8 -*-
"""FNPG_generation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hLjjGZflVW-HIu1S5DSFUiFcLf6pue5i

注意:
在 Colab 中运行此脚本前，请先在 Cell 中执行以下命令:
    from google.colab import drive
    drive.mount('/content/drive')
    import os
    os.chdir('/content/drive/My Drive')
    !pip install PyWavelets
"""

# from google.colab import drive
# drive.mount('/content/drive')

# import os
# os.chdir('/content/drive/My Drive')

# !pip install PyWavelets

import torch
import glob
import os
STAGE= 'GCRR'
STAGE_2= 'GRSB'
file_pattern_x = '/content/drive/MyDrive/logcompletion/data/Teamdata/complete_data_for_PIModel/train/Train_x_all_complete_*.pt'
file_pattern_y = '/content/drive/MyDrive/logcompletion/data/Teamdata/complete_data_for_PIModel/train/Train_y_all_complete_*.pt'
file_pattern_target = f'/content/drive/MyDrive/logcompletion/data/Teamdata/complete_data_for_PIModel/target_10/Target_{STAGE}_*.pt'
file_pattern_target_2 = f'/content/drive/MyDrive/logcompletion/data/Teamdata/complete_data_for_PIModel/target_10/Target_{STAGE_2}_*.pt'


"""
上面路径当中存储的tensor都是用512窗口去滑动每一口井得到的，所以每口井的尾端难免会舍弃一些，从而与原数据形状不一致。
现在考虑：反总标准化+反组标准化这些tensor.
试验后得出结论：反标准化只用在画图当中，训练终点就是两次标准化的数据吧。
画图时，拿出一条残井tensor，做成standard.ipynb文件里数据的形状，再进行两次反标准化吧。
仔细一想似乎有别的办法
"""
# Get all files matching the pattern
x_files = glob.glob(file_pattern_x)
y_files = glob.glob(file_pattern_y)
target_files = glob.glob(file_pattern_target)
target_files_2 = glob.glob(file_pattern_target_2)

# Sort the files to ensure they are in the correct order
x_files.sort()
y_files.sort()
target_files.sort()
target_files_2.sort()

# List to store individual tensors
tensor_list_x = []
tensor_list_y = []
tensor_list_target = []
tensor_list_target_2 = []

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

# file就是每口井
for file in x_files:
    # 查看tensor_list_x的测井顺序，用于提取井名
    print(f"Loading tensor from file: {file}")  # Print the file name
    tensor = torch.load(file,map_location=torch.device(device))
    well_len = tensor
    tensor_list_x.append(tensor)
print('\n')

for file in y_files:
    print(f"Loading tensor from file: {file}")  # Print the file name
    tensor = torch.load(file,map_location=torch.device(device))
    tensor_list_y.append(tensor)

print('\n')

for file in target_files:
    print(f"Loading tensor from file: {file}")  # Print the file name
    tensor = torch.load(file,map_location=torch.device(device))
    tensor_list_target.append(tensor)

print('\n')

for file in target_files_2:
    print(f"Loading tensor from file: {file}")  # Print the file name
    tensor = torch.load(file,map_location=torch.device(device))
    tensor_list_target_2.append(tensor)

# Concatenate all tensors along the first dimension
combined_tensor_x = torch.cat(tensor_list_x, dim=0)
combined_tensor_y = torch.cat(tensor_list_y, dim=0)
combined_tensor_target = torch.cat(tensor_list_target, dim=0)
combined_tensor_target_2 = torch.cat(tensor_list_target_2, dim=0)

print(f"Combined tensor shape: {combined_tensor_x.shape}")
print(f"Combined tensor shape: {combined_tensor_y.shape}")
print(f"Combined tensor shape: {combined_tensor_target.shape}")
print(f"Combined tensor shape: {combined_tensor_target_2.shape}")

local_train_csv = '/content/drive/MyDrive/well log data mixing&incrementation/CSV_train.csv'
import pandas as pd
train_ori_set_2 = pd.read_csv(local_train_csv, engine = 'python',sep=';')
print('训练集读取完成！')

#from re import T
import numpy as np
import pandas as pd
import random
from scipy import stats
import seaborn as sns
import matplotlib.pyplot as plt

# ============================================================================
# R1-10: 相关性矩阵分析 (Correlation Matrix Analysis)
# ============================================================================
def compute_correlation_matrix(input_tensor, target_tensor, input_names, target_names,
                                method='pearson', save_path=None):
    """
    计算输入特征与输出目标之间的相关性矩阵

    Args:
        input_tensor: 输入数据 (N, C_in, L) 或 (N, C_in)
        target_tensor: 目标数据 (N, C_out, L) 或 (N, C_out)
        input_names: 输入特征名称列表
        target_names: 输出特征名称列表
        method: 'pearson' 或 'spearman'
        save_path: 保存图片的路径

    Returns:
        corr_matrix: 相关性矩阵 DataFrame
    """
    # 转换为 numpy 并展平
    if isinstance(input_tensor, torch.Tensor):
        input_data = input_tensor.cpu().numpy()
        target_data = target_tensor.cpu().numpy()
    else:
        input_data = input_tensor
        target_data = target_tensor

    # 如果是3D张量，需要重塑
    if len(input_data.shape) == 3:
        N, C_in, L = input_data.shape
        input_data = input_data.transpose(0, 2, 1).reshape(-1, C_in)  # (N*L, C_in)
    if len(target_data.shape) == 3:
        N, C_out, L = target_data.shape
        target_data = target_data.transpose(0, 2, 1).reshape(-1, C_out)  # (N*L, C_out)

    # 合并数据
    all_names = input_names + target_names
    all_data = np.concatenate([input_data, target_data], axis=1)

    # 创建 DataFrame
    df = pd.DataFrame(all_data, columns=all_names)

    # 计算相关性矩阵
    if method == 'pearson':
        corr_matrix = df.corr(method='pearson')
    else:
        corr_matrix = df.corr(method='spearman')

    # 可视化
    fig, axes = plt.subplots(1, 2, figsize=(16, 6))

    # 完整相关性矩阵
    sns.heatmap(corr_matrix, annot=True, cmap='RdBu_r', center=0,
                fmt='.2f', ax=axes[0], vmin=-1, vmax=1,
                annot_kws={'size': 8})
    axes[0].set_title(f'Full Correlation Matrix ({method.capitalize()})', fontsize=12)

    # 输入-输出相关性矩阵（只显示输入与输出之间的相关性）
    input_output_corr = corr_matrix.loc[input_names, target_names]
    sns.heatmap(input_output_corr, annot=True, cmap='RdBu_r', center=0,
                fmt='.2f', ax=axes[1], vmin=-1, vmax=1,
                annot_kws={'size': 10})
    axes[1].set_title(f'Input-Output Correlation ({method.capitalize()})', fontsize=12)
    axes[1].set_xlabel('Output Features')
    axes[1].set_ylabel('Input Features')

    plt.tight_layout()

    if save_path:
        plt.savefig(save_path, dpi=300, bbox_inches='tight')
        print(f"相关性矩阵图已保存至: {save_path}")

    plt.show()

    # 打印关键统计信息
    print("\n" + "="*60)
    print("输入-输出相关性分析摘要")
    print("="*60)
    for target in target_names:
        print(f"\n{target} 与输入特征的相关性:")
        for inp in input_names:
            corr_val = corr_matrix.loc[inp, target]
            strength = "强" if abs(corr_val) > 0.7 else ("中等" if abs(corr_val) > 0.4 else "弱")
            print(f"  {inp}: {corr_val:.4f} ({strength}相关)")

    return corr_matrix

# ============================================================================
# R1-11: 训练/测试样本统计 (Train/Test Sample Statistics)
# ============================================================================
def compute_sample_statistics(tensor_data, feature_names, dataset_name="Dataset"):
    """
    计算数据集的统计信息

    Args:
        tensor_data: 数据张量 (N, C, L) 或 list of tensors
        feature_names: 特征名称列表
        dataset_name: 数据集名称

    Returns:
        stats_df: 统计信息 DataFrame
    """
    if isinstance(tensor_data, list):
        # 如果是tensor列表，先合并
        tensor_data = torch.cat(tensor_data, dim=0)

    if isinstance(tensor_data, torch.Tensor):
        data = tensor_data.cpu().numpy()
    else:
        data = tensor_data

    # 如果是3D张量 (N, C, L)
    if len(data.shape) == 3:
        N, C, L = data.shape
        n_samples = N
        seq_length = L
        # 重塑为 (N*L, C) 用于统计
        data_flat = data.transpose(0, 2, 1).reshape(-1, C)
    else:
        n_samples = data.shape[0]
        seq_length = 1
        data_flat = data
        C = data.shape[1] if len(data.shape) > 1 else 1

    print("\n" + "="*60)
    print(f"{dataset_name} 统计信息")
    print("="*60)
    print(f"样本数量 (N): {n_samples}")
    print(f"序列长度 (L): {seq_length}")
    print(f"特征数量 (C): {len(feature_names)}")
    print(f"总数据点数: {n_samples * seq_length}")

    # 计算每个特征的统计信息
    stats_dict = {
        'Feature': feature_names,
        'Mean': [],
        'Std': [],
        'Min': [],
        'Max': [],
        'Median': [],
        'Q1 (25%)': [],
        'Q3 (75%)': [],
        'Skewness': [],
        'Kurtosis': []
    }

    for i, name in enumerate(feature_names):
        feature_data = data_flat[:, i]
        stats_dict['Mean'].append(np.mean(feature_data))
        stats_dict['Std'].append(np.std(feature_data))
        stats_dict['Min'].append(np.min(feature_data))
        stats_dict['Max'].append(np.max(feature_data))
        stats_dict['Median'].append(np.median(feature_data))
        stats_dict['Q1 (25%)'].append(np.percentile(feature_data, 25))
        stats_dict['Q3 (75%)'].append(np.percentile(feature_data, 75))
        stats_dict['Skewness'].append(stats.skew(feature_data))
        stats_dict['Kurtosis'].append(stats.kurtosis(feature_data))

    stats_df = pd.DataFrame(stats_dict)
    print("\n特征统计信息:")
    print(stats_df.to_string(index=False))

    return stats_df

def plot_feature_distributions(tensor_data, feature_names, dataset_name="Dataset",
                                save_path=None, bins=50):
    """
    绘制特征分布直方图

    Args:
        tensor_data: 数据张量
        feature_names: 特征名称列表
        dataset_name: 数据集名称
        save_path: 保存路径
        bins: 直方图的bin数量
    """
    if isinstance(tensor_data, list):
        tensor_data = torch.cat(tensor_data, dim=0)

    if isinstance(tensor_data, torch.Tensor):
        data = tensor_data.cpu().numpy()
    else:
        data = tensor_data

    if len(data.shape) == 3:
        N, C, L = data.shape
        data_flat = data.transpose(0, 2, 1).reshape(-1, C)
    else:
        data_flat = data
        C = data.shape[1] if len(data.shape) > 1 else 1

    n_features = len(feature_names)
    n_cols = min(4, n_features)
    n_rows = (n_features + n_cols - 1) // n_cols

    fig, axes = plt.subplots(n_rows, n_cols, figsize=(4*n_cols, 3*n_rows))
    if n_features == 1:
        axes = [axes]
    else:
        axes = axes.flatten()

    for i, name in enumerate(feature_names):
        ax = axes[i]
        feature_data = data_flat[:, i]

        # 使用更宽松的百分位数范围（0.5%-99.5%）来移除极端异常值
        p_low = np.percentile(feature_data, 0.5)
        p_high = np.percentile(feature_data, 99.5)

        # 使用range参数限制直方图的数据范围
        ax.hist(feature_data, bins=bins, range=(p_low, p_high), density=True, alpha=0.7,
                color='steelblue', edgecolor='black', linewidth=0.5)
        ax.axvline(np.mean(feature_data), color='red', linestyle='--',
                   label=f'Mean: {np.mean(feature_data):.2f}')
        ax.axvline(np.median(feature_data), color='green', linestyle=':',
                   label=f'Median: {np.median(feature_data):.2f}')
        ax.set_xlabel(name, fontsize=10)
        ax.set_ylabel('Density', fontsize=10)
        ax.set_title(f'{name} Distribution', fontsize=11)
        ax.legend(fontsize=8)
        ax.grid(True, alpha=0.3)

    # 隐藏多余的子图
    for i in range(n_features, len(axes)):
        axes[i].set_visible(False)

    plt.suptitle(f'{dataset_name} Feature Distributions', fontsize=14, y=1.02)
    plt.tight_layout()

    if save_path:
        plt.savefig(save_path, dpi=300, bbox_inches='tight')
        print(f"分布图已保存至: {save_path}")

    plt.show()

def compare_train_test_statistics(train_data, test_data, feature_names, save_path=None):
    """
    比较训练集和测试集的统计特性

    Args:
        train_data: 训练数据张量
        test_data: 测试数据张量
        feature_names: 特征名称列表
        save_path: 保存路径
    """
    # 计算统计信息
    train_stats = compute_sample_statistics(train_data, feature_names, "Training Set")
    test_stats = compute_sample_statistics(test_data, feature_names, "Test Set")

    # 可视化对比
    n_features = len(feature_names)
    fig, axes = plt.subplots(2, n_features, figsize=(4*n_features, 8))

    if isinstance(train_data, torch.Tensor):
        train_np = train_data.cpu().numpy()
        test_np = test_data.cpu().numpy()
    else:
        train_np = train_data
        test_np = test_data

    if len(train_np.shape) == 3:
        train_flat = train_np.transpose(0, 2, 1).reshape(-1, train_np.shape[1])
        test_flat = test_np.transpose(0, 2, 1).reshape(-1, test_np.shape[1])
    else:
        train_flat = train_np
        test_flat = test_np

    for i, name in enumerate(feature_names):
        # 直方图对比
        ax1 = axes[0, i] if n_features > 1 else axes[0]
        ax1.hist(train_flat[:, i], bins=50, density=True, alpha=0.5,
                 label='Train', color='blue')
        ax1.hist(test_flat[:, i], bins=50, density=True, alpha=0.5,
                 label='Test', color='orange')
        ax1.set_title(f'{name}', fontsize=11)
        ax1.set_xlabel('Value')
        ax1.set_ylabel('Density')
        ax1.legend()
        ax1.grid(True, alpha=0.3)

        # 箱线图对比
        ax2 = axes[1, i] if n_features > 1 else axes[1]
        bp = ax2.boxplot([train_flat[:, i], test_flat[:, i]],
                         labels=['Train', 'Test'], patch_artist=True)
        bp['boxes'][0].set_facecolor('lightblue')
        bp['boxes'][1].set_facecolor('lightorange')
        ax2.set_title(f'{name} Comparison', fontsize=11)
        ax2.set_ylabel('Value')
        ax2.grid(True, alpha=0.3)

    plt.suptitle('Train vs Test Distribution Comparison', fontsize=14, y=1.02)
    plt.tight_layout()

    if save_path:
        plt.savefig(save_path, dpi=300, bbox_inches='tight')
        print(f"对比图已保存至: {save_path}")

    plt.show()

    return train_stats, test_stats

# ============================================================================
# 执行 R1-10 和 R1-11 分析
# ============================================================================
print("\n" + "="*70)
print("开始执行数据分析 (R1-10 & R1-11)")
print("="*70)

# 定义特征名称
input_feature_names = ['GR', 'RHOB', 'NPHI', 'DTC']  # 输入特征
target_feature_names_GCRR = ['RSHA', 'RMED', 'RDEP', 'SP']  # GCRR目标（移除CALI）
target_feature_names_GRSB = ['RSHA', 'RMED']  # GRSB目标（部分）

# 从原始数据中提取完整的特征数据（用于R1-10和R1-11分析）
print("\n从原始数据中提取完整特征...")

# 合并输入和目标特征列名，一次性提取所有需要的列
all_feature_names = input_feature_names + target_feature_names_GCRR
print(f"提取特征: {all_feature_names}")

# 提取所有特征并删除包含NaN的行
data_full = train_ori_set_2[all_feature_names].dropna()
print(f"原始数据行数: {len(train_ori_set_2)}, 删除NaN后行数: {len(data_full)}")

# 分离输入和目标特征
input_data_full = data_full[input_feature_names].values  # (N_clean, 4)
target_data_full = data_full[target_feature_names_GCRR].values  # (N_clean, 4)

# 转换为tensor格式（添加序列维度以匹配原有数据格式）
input_tensor_full = torch.tensor(input_data_full, dtype=torch.float32).unsqueeze(-1)  # (N, 4, 1)
target_tensor_full = torch.tensor(target_data_full, dtype=torch.float32).unsqueeze(-1)  # (N, 4, 1)

print(f"输入特征数据形状: {input_tensor_full.shape}")
print(f"目标特征数据形状: {target_tensor_full.shape}")

# R1-11: 样本统计
print("\n>>> R1-11: 训练/测试样本统计分析")
print("-" * 50)

# 输入数据统计
input_stats = compute_sample_statistics(
    input_tensor_full,
    input_feature_names,
    "Input Features"
)

# 目标数据统计（不包含CALI）
target_stats = compute_sample_statistics(
    target_tensor_full,
    target_feature_names_GCRR,
    "Target Features (without CALI)"
)

# 绘制分布图
print("\n绘制输入特征分布图...")
plot_feature_distributions(
    input_tensor_full,
    input_feature_names,
    "Input Features",
    save_path='/content/drive/MyDrive/logcompletion/figure/R1_11_input_distributions.pdf'
)

print("\n绘制目标特征分布图...")
plot_feature_distributions(
    target_tensor_full,
    target_feature_names_GCRR,
    "Target Features (without CALI)",
    save_path='/content/drive/MyDrive/logcompletion/figure/R1_11_target_distributions.pdf'
)

# R1-10: 相关性矩阵
print("\n>>> R1-10: 相关性矩阵分析")
print("-" * 50)

# 计算 Pearson 相关性
print("\nPearson 相关性矩阵:")
pearson_corr = compute_correlation_matrix(
    input_tensor_full,
    target_tensor_full,
    input_feature_names,
    target_feature_names_GCRR,
    method='pearson',
    save_path='/content/drive/MyDrive/logcompletion/figure/R1_10_correlation_pearson.pdf'
)

# 计算 Spearman 相关性
print("\nSpearman 相关性矩阵:")
spearman_corr = compute_correlation_matrix(
    input_tensor_full,
    target_tensor_full,
    input_feature_names,
    target_feature_names_GCRR,
    method='spearman',
    save_path='/content/drive/MyDrive/logcompletion/figure/R1_10_correlation_spearman.pdf'
)

print("\n" + "="*70)
print("R1-10 & R1-11 数据分析完成!")
print("="*70)



from matplotlib import pyplot as plt
import time

import torch
from torch.utils.data import TensorDataset, DataLoader
import torch.nn.functional as F
import torch.nn as nn
from tqdm import tqdm
from torch.optim import lr_scheduler
from math import exp
#import argparse
#from re import T

import os

#from pickle import TRUE

from typing import Union, Tuple, Optional
from torch.autograd import Variable


import math
from typing import Union, Tuple, Optional

from torch.utils.data import Dataset
from torch import Tensor
from torch.nn import Parameter

class Data:
    def __init__(self, input_sam, label):
        self.x = input_sam
        self.y = label
    def to(self, device):
        self.x = self.x.to(device)
        self.y = self.y.to(device)
        return self
class my_dataset(Dataset):
    def __init__(self, input, target):
        self.input = input  # (2035, 4, 512)
        self.target = target  # (2035, 1, 512)

    def __getitem__(self, idx):
        input_sam = self.input[idx]  # This will be of shape (4, 512)
        label = self.target[idx]  # This will be of shape (1, 512)

        # 如果input和target不是torch.Tensor，我们需要转换它们
        if not isinstance(input_sam, torch.Tensor):
            input_sam = torch.tensor(input_sam, dtype=torch.float32)
        if not isinstance(label, torch.Tensor):
            label = torch.tensor(label, dtype=torch.float32)

        # 返回Data对象
        return Data(input_sam=input_sam, label=label)

    def __len__(self):
        return len(self.input)

def custom_collate(batch):
    input_sam = torch.stack([item.x for item in batch])
    label = torch.stack([item.y for item in batch])
    return Data(input_sam=input_sam, label=label)

from functools import reduce
import operator
def count_params(model):
    c = 0
    for p in list(model.parameters()):
        c += reduce(operator.mul,
                    list(p.size()+(2,) if p.is_complex() else p.size()))
    return print(c)

#convolution in channel features
class conv_obj(nn.Module):
    def __init__(
        self,
        _in_channels: Union[int, Tuple[int, int]],
        _out_channels: int,
        cnn_in_channels: int,
        cnn_out_channels: int,
        batchsize: int = 3,
        down_up: bool = True, #default True == down
        poolstride: int = 2,
        onlypoolout:bool = True,
    ):
        super(conv_obj, self).__init__()
        self._in_channels = _in_channels
        self._out_channels = _out_channels
        self.cnn_in_channels = cnn_in_channels
        self.cnn_out_channels = cnn_out_channels
        self.batchsize = batchsize
        self.down_up = down_up
        self.poolstride = poolstride
        self.onlypoolout = onlypoolout


        if isinstance(_in_channels, int):
            _in_channels = (_in_channels, _in_channels)

        self.device = device
        print('device used in conv_obj：',self.device)


        if self.down_up == True:
            self.conv0 =  conv_down_conv_obj(cnn_in_channels,cnn_out_channels,onlypoolout,poolstride).to(self.device)
            self.conv1 =  conv_down_conv_obj(cnn_in_channels,cnn_out_channels,onlypoolout,poolstride).to(self.device)
            self.conv2 =  conv_down_conv_obj(cnn_in_channels,cnn_out_channels,onlypoolout,poolstride).to(self.device)
            self.conv3 =  conv_down_conv_obj(cnn_in_channels,cnn_out_channels,onlypoolout,poolstride).to(self.device)
        else:
            self.conv0 = conv_up_conv_obj(cnn_in_channels,cnn_out_channels,poolstride).to(self.device)
            self.conv1 = conv_up_conv_obj(cnn_in_channels,cnn_out_channels,poolstride).to(self.device)
            self.conv2 = conv_up_conv_obj(cnn_in_channels,cnn_out_channels,poolstride).to(self.device)
            self.conv3 = conv_up_conv_obj(cnn_in_channels,cnn_out_channels,poolstride).to(self.device)

    def forward(self, x):

        CIN,COUT,GIN,GOUT = self.cnn_in_channels,self.cnn_out_channels,self._in_channels,self._out_channels
        #print(x.shape)

        y = torch.zeros([self.batchsize,COUT,GOUT]).to(self.device)

        out_cat = torch.zeros([self.batchsize,COUT,GIN]).to(self.device)

        #print(x[0][0:self.batchsize * 4:4][:].shape)
        #print('y',y.shape)
        if self.onlypoolout == True:
            y[0 :self.batchsize * 4:4][:] = self.conv0(x[0:self.batchsize * 4:4][:])
            y[1 :self.batchsize * 4:4][:] = self.conv1(x[1:self.batchsize * 4:4][:])
            y[2 :self.batchsize * 4:4][:] = self.conv2(x[2:self.batchsize * 4:4][:])
            y[3 :self.batchsize * 4:4][:] = self.conv3(x[3:self.batchsize * 4:4][:])
        else:
            #temp = self.conv0(x[0][0:self.batchsize * 4:4][:])
            #print('temp length ',len(temp))
            #print('temp ',temp[0].shape)
            y[0 :self.batchsize * 4:4][:], out_cat[0 :self.batchsize * 4:4][:] = self.conv0(x[0:self.batchsize * 4:4][:])
            y[1 :self.batchsize * 4:4][:], out_cat[1 :self.batchsize * 4:4][:] = self.conv1(x[1:self.batchsize * 4:4][:])
            y[2 :self.batchsize * 4:4][:], out_cat[2 :self.batchsize * 4:4][:] = self.conv2(x[2:self.batchsize * 4:4][:])
            y[3 :self.batchsize * 4:4][:], out_cat[3 :self.batchsize * 4:4][:] = self.conv3(x[3:self.batchsize * 4:4][:])

        return y, out_cat

#用于conv_obj的下采样卷积模块
class conv_down_conv_obj(nn.Module):
    def __init__(self,in_ch,out_ch,onlypoolout,poolstride = 2):
        super(conv_down_conv_obj, self).__init__()
        self.onlypoolout = onlypoolout
        self.Conv = nn.Sequential(
            nn.Conv1d(in_channels=in_ch,out_channels=out_ch,kernel_size=7,stride=1,padding=3),
            nn.BatchNorm1d(out_ch),
            nn.LeakyReLU(negative_slope=0.2),
            #nn.ELU(),

            nn.Conv1d(in_channels=out_ch,out_channels=out_ch,kernel_size=7,stride=1,padding=3),
            nn.BatchNorm1d(out_ch),
            nn.LeakyReLU(negative_slope=0.2),
            #nn.ELU()
        )

        self.downsample= nn.Sequential(
            nn.MaxPool1d(5, stride=poolstride,padding = 2)
        )


    def forward(self,x):

        out_cat = self.Conv(x)
        out=self.downsample(out_cat)
        #print('out.size()',out.size(),'out.dtype',out.dtype,'out.type()',out.type())

        if self.onlypoolout==True:
            return out
        else:
            return out, out_cat

#用于conv_obj的上采样卷积模块
class conv_up_conv_obj(nn.Module):
    def __init__(self,in_ch,out_ch,poolstride = 2):
        super(conv_up_conv_obj, self).__init__()

        self.layers = nn.Sequential(
            nn.Conv1d(in_channels = in_ch, out_channels = 2*out_ch, kernel_size=7, stride=1, padding=3),
            nn.BatchNorm1d(2*out_ch),
            nn.LeakyReLU(negative_slope=0.2),
            #nn.ELU(),

            nn.Conv1d(in_channels = 2*out_ch, out_channels = 2*out_ch, kernel_size=7, stride=1, padding=3),
            nn.BatchNorm1d(2*out_ch),
            nn.LeakyReLU(negative_slope=0.2),

            nn.ConvTranspose1d(in_channels=2*out_ch,out_channels=out_ch,kernel_size=7,stride=poolstride,padding=3,output_padding=(poolstride-1)),
            nn.BatchNorm1d(out_ch),
            nn.LeakyReLU(negative_slope=0.2),
            #nn.ELU(),
        )

    def forward(self,x):
        out = self.layers(x)

        return out

#Unet结构上下采样部分的中间衔接（上采样）
class upsample(nn.Module):
    '''仅进行上采样（将上采样与和聚合模块分割开）'''
    def __init__(self,gnn_out_ch, cnn_in_ch, cnn_out_ch, bsize, poolstride=2):
        super(upsample,self).__init__()
        self.bsize = bsize
        self.cout = cnn_out_ch
        self.gout = gnn_out_ch

        self.conv1 = conv_up_conv_obj(cnn_in_ch,cnn_out_ch,poolstride)
        self.conv0 = conv_up_conv_obj(cnn_in_ch,cnn_out_ch,poolstride)
        self.conv2 = conv_up_conv_obj(cnn_in_ch,cnn_out_ch,poolstride)
        self.conv3 = conv_up_conv_obj(cnn_in_ch,cnn_out_ch,poolstride)

    def forward(self,x):
        y = torch.zeros([self.bsize, self.cout, self.gout]).to(device)

        y[0 :self.bsize * 4:4][:] = self.conv0(x[0:self.bsize * 4:4][:])
        y[1 :self.bsize * 4:4][:] = self.conv1(x[1:self.bsize * 4:4][:])
        y[2 :self.bsize * 4:4][:] = self.conv2(x[2:self.bsize * 4:4][:])
        y[3 :self.bsize * 4:4][:] = self.conv3(x[3:self.bsize * 4:4][:])

        return y

#Unet结构下采样部分中，补偿torch.cat导致的通道数翻倍
class cat_fuse(nn.Module):
    """
    卷积模块，减半通道数。
    """
    def __init__(self,cnn_in_ch,cnn_out_ch):
        super(cat_fuse,self).__init__()

        self.Conv = nn.Sequential(
            nn.Conv1d(in_channels=cnn_in_ch,out_channels=cnn_out_ch,kernel_size=7,stride=1,padding=3),
            nn.BatchNorm1d(cnn_out_ch),
            nn.LeakyReLU(negative_slope=0.2),
        )
    def forward(self,x):
        y = self.Conv(x)

        return y

#mlp用于学习mean与std
class mean_std_head(torch.nn.Module):
    def __init__(self):
        super(mean_std_head, self).__init__()

        self.mlp1 = MLP(4*512, 4*128, 4*32)
        self.mlp2 = MLP(4*32, 4*8, 8)

        #self.dropout = nn.Dropout(p=0.5)


    def forward(self, x, batch):

        y = torch.stack(unbatch(x, batch))
        y = torch.flatten(y,1,-1)

        y = self.mlp1(y)
        #y = self.dropout(y)
        y = self.mlp2(y)
        #y = self.dropout(y)
        #print('全连接后y', y.size(), y)

        return y


class MLP(torch.nn.Module):
    def __init__(self, in_ch, hid_ch, out_ch):
        super(MLP, self).__init__()

        self.mlp = nn.Sequential(
            nn.Linear(in_ch, hid_ch),
            nn.LeakyReLU(negative_slope=0.2),

            nn.Linear(hid_ch, hid_ch),
            nn.LeakyReLU(negative_slope=0.2),

            nn.Linear(hid_ch, out_ch),
        )

    def forward(self, x):
        x = self.mlp(x)

        return x

# Fourier Feature Extractor core
class SpectralConv1d(nn.Module):
    def __init__(self, in_channels, out_channels, modes1):
        super(SpectralConv1d, self).__init__()

        """
        3D Fourier layer. It does FFT, linear transform, and Inverse FFT.
        """

        self.in_channels = in_channels
        self.out_channels = out_channels
        self.modes1 = modes1 #Number of Fourier modes to multiply, at most floor(N/2) + 1


        self.scale = (1 / (in_channels * out_channels))
        self.weights1 = nn.Parameter(self.scale * torch.rand(in_channels, out_channels, self.modes1, dtype=torch.cfloat))
        self.weights2 = nn.Parameter(self.scale * torch.rand(in_channels, out_channels, self.modes1, dtype=torch.cfloat))
        self.weights3 = nn.Parameter(self.scale * torch.rand(in_channels, out_channels, self.modes1, dtype=torch.cfloat))
        self.weights4 = nn.Parameter(self.scale * torch.rand(in_channels, out_channels, self.modes1, dtype=torch.cfloat))

    # Complex multiplication
    def compl_mul1d(self, input, weights):
        # (batch, in_channel, x), (in_channel, out_channel, x) -> (batch, out_channel, x)
        return torch.einsum("bix,iox->box", input, weights)

    def forward(self, x):
        batchsize = x.shape[0]
        #Compute Fourier coeffcients up to factor of e^(- something constant)
        x_ft = torch.fft.rfftn(x, dim=[-1]).to(x.device)

        # Multiply relevant Fourier modes
        out_ft = torch.zeros(batchsize, self.out_channels, x.size(-1)//2 + 1, dtype=torch.cfloat, device=x.device)
        out_ft[:, :, :self.modes1] = \
            self.compl_mul1d(x_ft[:, :, :self.modes1], self.weights1.to(x.device))
        out_ft[:, :, -self.modes1:] = \
            self.compl_mul1d(x_ft[:, :, -self.modes1:], self.weights2.to(x.device))
        out_ft[:, :, :self.modes1] = \
            self.compl_mul1d(x_ft[:, :, :self.modes1], self.weights3.to(x.device))
        out_ft[:, :, -self.modes1:] = \
            self.compl_mul1d(x_ft[:, :, -self.modes1:], self.weights4.to(x.device))

        #Return to physical space
        x = torch.fft.irfftn(out_ft, s=(x.size(-1)))
        return x

class MLP_(nn.Module):
    def __init__(self, in_channels, out_channels, mid_channels):
        super(MLP_, self).__init__()
        self.mlp1 = nn.Conv1d(in_channels, mid_channels, 1)
        self.mlp2 = nn.Conv1d(mid_channels, out_channels, 1)

    def forward(self, x):
        x = self.mlp1(x)
        x = F.gelu(x)
        x = self.mlp2(x)
        return x

class FourierFeatureExtractor(nn.Module):
    def __init__(self, in_channels=4, out_channels=1, mid_channels=8, modes1=8):
        super(FourierFeatureExtractor,self).__init__()
        self.fconv1 = SpectralConv1d(in_channels, mid_channels, modes1)
        self.fconv2 = SpectralConv1d(mid_channels, mid_channels, modes1)
        self.fconv3 = SpectralConv1d(mid_channels, mid_channels, modes1)
        self.mlp1 = MLP_(mid_channels, mid_channels, mid_channels)
        self.mlp2 = MLP_(mid_channels, mid_channels, mid_channels)
        self.mlp3 = MLP_(mid_channels, mid_channels, mid_channels)
        self.w1 = nn.Conv1d(in_channels, mid_channels, 1)
        self.w2 = nn.Conv1d(mid_channels, mid_channels, 1)
        self.w3 = nn.Conv1d(mid_channels, mid_channels, 1)
        self.out_proj = MLP_(mid_channels, out_channels, mid_channels)


    def forward(self,x):
        # x (32,4,512)
        # f-1
        x_f = self.fconv1(x)
        x_f = self.mlp1(x_f)

        # c-1
        x_c =self.w1(x)

        x = x_f + x_c
        x = F.gelu(x)
        # f-2
        x_f = self.fconv2(x)
        x_f = self.mlp2(x_f)

        # c-2
        x_c =self.w2(x)
        x = x_f + x_c
        x = F.gelu(x)

        # f-3
        x_f = self.fconv3(x)
        x_f = self.mlp3(x_f)

        # c-3
        x_c =self.w3(x)
        x = x_f + x_c
        x = F.gelu(x)

        x = self.out_proj(x)
        return x


# U-Net
#meta model to be trained
class FNPG(torch.nn.Module):

    def __init__(self, gnn_ch, batchsize, fea_litho, head, drop, modes1=16):
        super(FNPG, self).__init__()
        """
        input:(batch_size,num_curves,channels,sam_len)
        output:(batch_size,num_curves,sam_len)

        Args:
            modes1: 傅里叶模式数 (kmax)，控制频域中保留的模式数量
        """
        CNN_ch = [4,32,64,128,256,512] #gnn_ch = [512,256,128,64,32]

        result_ch=5

        self.bsize = batchsize
        self.fea_n = len(fea_litho)
        self.modes1 = modes1  # 保存 kmax 参数

        #self.head = mean_std_head()#到底还用不用神经网络去反标准化了？
        self.gd0 = conv_obj(gnn_ch[0],gnn_ch[1],CNN_ch[0],CNN_ch[1],batchsize = batchsize,onlypoolout=False,down_up = True)
        self.gd1 = conv_obj(gnn_ch[1],gnn_ch[2],CNN_ch[1],CNN_ch[2],batchsize = batchsize,onlypoolout=False,down_up = True)
        self.gd2 = conv_obj(gnn_ch[2],gnn_ch[3],CNN_ch[2],CNN_ch[3],batchsize = batchsize,onlypoolout=False,down_up = True)

        self.FFE_up1 = FourierFeatureExtractor(CNN_ch[1],CNN_ch[1], mid_channels=32, modes1=modes1)
        self.FFE_up2 = FourierFeatureExtractor(CNN_ch[2],CNN_ch[2], mid_channels=32, modes1=modes1)
        self.FFE_up3 = FourierFeatureExtractor(CNN_ch[3],CNN_ch[3], mid_channels=32, modes1=modes1)


        self.u0 = upsample(gnn_ch[2],CNN_ch[3],CNN_ch[3], bsize=batchsize, poolstride=2).to(device)
        self.cat0 =cat_fuse(CNN_ch[4],CNN_ch[3]).to(device)

        self.u1 = upsample(gnn_ch[1],CNN_ch[3],CNN_ch[2], bsize=batchsize, poolstride=2).to(device)
        self.cat1 =cat_fuse(CNN_ch[3],CNN_ch[2]).to(device)

        self.u2 = upsample(gnn_ch[0],CNN_ch[2],CNN_ch[1], bsize=batchsize, poolstride=2).to(device)
        self.cat2 =cat_fuse(CNN_ch[2],CNN_ch[1]).to(device)

        self.FFE_down1 = FourierFeatureExtractor(CNN_ch[1],CNN_ch[1], mid_channels=32, modes1=modes1)
        self.FFE_down2 = FourierFeatureExtractor(CNN_ch[2],CNN_ch[2], mid_channels=32, modes1=modes1)
        self.FFE_down3 = FourierFeatureExtractor(CNN_ch[3],CNN_ch[3], mid_channels=32, modes1=modes1)


        self.result = nn.Sequential(
            nn.Conv1d(CNN_ch[1],CNN_ch[1],kernel_size=7,stride=1,padding=3),
            nn.BatchNorm1d(CNN_ch[1]),
            nn.LeakyReLU(negative_slope=0.2),

            nn.Conv1d(CNN_ch[1],CNN_ch[1],kernel_size=7,stride=1,padding=3),
            nn.BatchNorm1d(CNN_ch[1]),
            nn.LeakyReLU(negative_slope=0.2),

            nn.Conv1d(CNN_ch[1],result_ch,kernel_size=7,stride=1,padding=3),
        )

    def forward(self,data):
        x = data.x

        out, cat0 = self.gd0(x)

        out = self.FFE_up1(out)

        out, cat1 = self.gd1(out)

        out = self.FFE_up2(out)

        out, cat2 = self.gd2(out)

        out = self.FFE_up3(out)

        out = self.u0(out)

        out = torch.cat((cat2,out),dim=1)

        out = self.cat0(out)

        out = self.FFE_down3(out)

        out = self.u1(out)

        out = torch.cat((cat1,out),dim=1)

        out = self.cat1(out)
        out = self.FFE_down2(out)

        out = self.u2(out)

        out = torch.cat((cat0,out),dim=1)

        out = self.cat2(out)
        out = self.FFE_down1(out)


        out = self.result(out)
        out = out.squeeze(1)

        return out

from types import SimpleNamespace

# 因为要做4预测7的实验，路径用老的{STAGE}检索不合适，附一个的吧
STAGE = 'GCRR_GRSB'
os.makedirs(f'/content/drive/MyDrive/logcompletion/model/ctra_exp_{STAGE}/',exist_ok=True)
os.makedirs(f'/content/drive/MyDrive/logcompletion/figure/ctra_exp_{STAGE}/',exist_ok=True)
os.makedirs(f'/content/drive/MyDrive/logcompletion/loss_{STAGE}/',exist_ok=True)
args = SimpleNamespace(
    batch_size=600,#600
    sam_num=2560,
    epochs=1,
    save_model_path=f'/content/drive/MyDrive/logcompletion/model/ctra_exp_{STAGE}/',
    lossfigpath=f'/content/drive/MyDrive/logcompletion/figure/ctra_exp_{STAGE}/',
    sam_len=512,
    graph_channels=[512,256,128,64,32],
    data_norm_type='',
    LR=0.00001,
    #['RHOB', 'NPHI', 'DTC', 'RDEP', 'SP'，'BS']
    fea_litho=['GR', 'RHOB', 'NPHI', 'DTC'],
    need_maskd=True,
    filePath='/content/drive/MyDrive/logcompletion/data/Teamdata/standard_wells/data2/',
    loss_name=f'/content/drive/MyDrive/logcompletion/loss_{STAGE}/loss_init.npz',
    filt_size=19,
    drop=0,
    head=1
)

class CustomLossWithAdaptiveDerivativePenalty(nn.Module):
    """
    自定义损失函数，结合均方误差、导数惩罚和真实值导数的MSE。
    """
    def __init__(self, sequence_length=512, init_alpha=0.1, init_beta=0.01):
        super().__init__()
        self.sequence_length = sequence_length
        self.mse = nn.MSELoss()

        # 将 alpha 和 beta 设置为可学习的参数
        self.log_alpha = nn.Parameter(torch.log(torch.tensor(init_alpha)))
        self.log_beta = nn.Parameter(torch.log(torch.tensor(init_beta)))

    def forward(self, y_pred, y_true):
        # 基本MSE损失
        mse_loss = self.mse(y_pred, y_true)

        # 计算 y_pred 的一阶导数（使用中心差分法，考虑边界）
        dy_pred = torch.zeros_like(y_pred)
        dy_pred[:, :, 1:-1] = (y_pred[:, :, 2:] - y_pred[:, :, :-2]) / 2
        dy_pred[:, :, 0] = y_pred[:, :, 1] - y_pred[:, :, 0]  # 前边界
        dy_pred[:, :, -1] = y_pred[:, :, -1] - y_pred[:, :, -2]  # 后边界

        # 计算 y_true 的一阶导数（使用中心差分法，考虑边界）
        dy_true = torch.zeros_like(y_true)
        dy_true[:, :, 1:-1] = (y_true[:, :, 2:] - y_true[:, :, :-2]) / 2
        dy_true[:, :, 0] = y_true[:, :, 1] - y_true[:, :, 0]  # 前边界
        dy_true[:, :, -1] = y_true[:, :, -1] - y_true[:, :, -2]  # 后边界

        # 计算一阶导数的MSE损失
        derivative_mse_loss = self.mse(dy_pred, dy_true)

        # 计算二阶导数（考虑边界）
        d2y = torch.zeros_like(y_pred)
        d2y[:, :, 1:-1] = y_pred[:, :, 2:] - 2 * y_pred[:, :, 1:-1] + y_pred[:, :, :-2]
        d2y[:, :, 0] = y_pred[:, :, 2] - 2 * y_pred[:, :, 1] + y_pred[:, :, 0]
        d2y[:, :, -1] = y_pred[:, :, -1] - 2 * y_pred[:, :, -2] + y_pred[:, :, -3]

        # 使用 exp 来确保 alpha 和 beta 始终为正
        alpha = torch.exp(self.log_alpha)
        beta = torch.exp(self.log_beta)

        # 计算导数惩罚
        derivative_penalty = -alpha * torch.mean(torch.abs(dy_pred)) + beta * torch.mean(torch.square(d2y))
        #print(mse_loss.shape, derivative_mse_loss.shape, derivative_penalty.shape)
        # 总损失
        total_loss = mse_loss + 1 * derivative_mse_loss + 1 * derivative_penalty

        return total_loss

    def get_alpha_beta(self):
        return torch.exp(self.log_alpha).item(), torch.exp(self.log_beta).item()

import pywt
class CustomLossWithAdaptiveDerivativePenaltyAndWavelet(nn.Module):
    def __init__(self, sequence_length=512, init_alpha=0.1, init_beta=0.01, init_gamma=0.1, wavelet='db4', mode='zero', level=None):
        super().__init__()
        self.sequence_length = sequence_length
        self.mse = nn.MSELoss()
        self.mse_none = nn.MSELoss(reduction='none')


        self.log_alpha = nn.Parameter(torch.log(torch.tensor(init_alpha)))
        self.log_beta = nn.Parameter(torch.log(torch.tensor(init_beta)))
        self.log_gamma = nn.Parameter(torch.log(torch.tensor(init_gamma)))

        self.wavelet = wavelet
        self.mode = mode
        self.level = level

    def wavelet_transform(self, x):
        # 对输入进行小波变换并重构为原始长度
        coeffs = []
        for i in range(x.shape[0]):
            for j in range(x.shape[1]):
                # 进行小波分解
                coeff = pywt.wavedec(x[i, j].cpu().numpy(), self.wavelet, mode=self.mode, level=self.level)

                # 保留近似系数，将细节系数置零
                new_coeffs = [coeff[0]] + [np.zeros_like(c) for c in coeff[1:]]

                # 重构信号
                reconstructed = pywt.waverec(new_coeffs, self.wavelet, mode=self.mode)

                # 确保重构信号长度与原始信号相同
                if len(reconstructed) > self.sequence_length:
                    reconstructed = reconstructed[:self.sequence_length]
                elif len(reconstructed) < self.sequence_length:
                    reconstructed = np.pad(reconstructed, (0, self.sequence_length - len(reconstructed)))

                coeffs.append(torch.tensor(reconstructed).to(x.device))

        return torch.stack(coeffs).view(x.shape)

    def forward(self, y_pred, y_true):
        # 基本MSE损失
        mse_loss = F.mse_loss(y_pred, y_true)

        # 计算 y_pred 的一阶导数
        dy_pred = torch.zeros_like(y_pred)
        dy_pred[:, :, 1:-1] = (y_pred[:, :, 2:] - y_pred[:, :, :-2]) / 2
        dy_pred[:, :, 0] = y_pred[:, :, 1] - y_pred[:, :, 0]
        dy_pred[:, :, -1] = y_pred[:, :, -1] - y_pred[:, :, -2]

        # 计算 y_true 的一阶导数
        dy_true = torch.zeros_like(y_true)
        dy_true[:, :, 1:-1] = (y_true[:, :, 2:] - y_true[:, :, :-2]) / 2
        dy_true[:, :, 0] = y_true[:, :, 1] - y_true[:, :, 0]
        dy_true[:, :, -1] = y_true[:, :, -1] - y_true[:, :, -2]

        # 计算一阶导数的MSE损失
        derivative_mse_loss = self.mse_none(dy_pred, dy_true)

        # 计算二阶导数
        d2y = torch.zeros_like(y_pred)
        d2y[:, :, 1:-1] = y_pred[:, :, 2:] - 2 * y_pred[:, :, 1:-1] + y_pred[:, :, :-2]
        d2y[:, :, 0] = y_pred[:, :, 2] - 2 * y_pred[:, :, 1] + y_pred[:, :, 0]
        d2y[:, :, -1] = y_pred[:, :, -1] - 2 * y_pred[:, :, -2] + y_pred[:, :, -3]

        alpha = torch.exp(self.log_alpha)
        beta = torch.exp(self.log_beta)
        gamma = torch.exp(self.log_gamma)

        # 计算导数惩罚
        derivative_penalty = -alpha * torch.mean(torch.abs(dy_pred)) + beta * torch.mean(torch.square(d2y))

        # 计算小波系数并用作权重
        wavelet_coeffs = self.wavelet_transform(y_true)
        weights = torch.abs(wavelet_coeffs)
        weights = weights / (weights.sum(dim=-1, keepdim=True) + 1e-8)
        #print('weights',weights.shape)
        #print('mse_loss',mse_loss.shape)


        # 应用权重到MSE损失
        weighted_mse_loss = (mse_loss * (1 + gamma * weights)).mean()
        weighted_derivative_mse_loss = (derivative_mse_loss * (1 + weights)).mean() #alpha之前是造成负值loss的derivative_penalty中的一个系数

        # 总损失
        total_loss = weighted_mse_loss + weighted_derivative_mse_loss #+ derivative_penalty
        #total_loss = F.relu(total_loss)
        return total_loss


    def get_alpha_beta_gamma(self):
        return torch.exp(self.log_alpha).item(), torch.exp(self.log_beta).item(), torch.exp(self.log_gamma).item()

# 神经网络最佳模型保存与加载
def save_checkpoint(model, optimizer, epoch, best_val_loss, path):
    torch.save({
        'epoch': epoch,
        'model_state_dict': model.state_dict(),
        'optimizer_state_dict': optimizer.state_dict(),
        'best_val_loss': best_val_loss,
    }, path)

def load_best_model(model, optimizer, path):
    checkpoint = torch.load(path)
    model.load_state_dict(checkpoint['model_state_dict'])
    optimizer.load_state_dict(checkpoint['optimizer_state_dict'])
    return model, optimizer, checkpoint['epoch'], checkpoint['best_val_loss']





"""## after-process"""

#拿个井做整井的预测成图 注意index
well_x_pt = tensor_list_x[0].clone()#tensor_list_x的有91个items，对应91口井
well_y_pt = tensor_list_y[0].clone()

#第一口井是15/9-15 注意index
# 移除CALI通道：[:,2:,:] 跳过深度列(0)和CALI列(1)，只保留RSHA, RMED
well_list_target_ = torch.cat((tensor_list_target[0][:,2:,:].clone(),tensor_list_target_2[0][:,1:3,:].clone()),dim=1)
#well_list_target_ = tensor_list_target[0][:,1,:].clone().unsqueeze(1)
well_target_pt = well_list_target_.clone()

well_x_pt.shape, well_y_pt.shape, well_target_pt.shape

# 这个cell不运行
well_x_pt_2 = tensor_list_x[1].clone()#tensor_list_x的有91个items，对应91口井
well_y_pt_2 = tensor_list_y[1].clone()

#第二口井是15/9-17 注意index
# 移除CALI通道：[:,2:,:] 跳过深度列(0)和CALI列(1)，只保留RSHA, RMED
well_list_target_2 = torch.cat((tensor_list_target[1][:,2:,:].clone(),tensor_list_target_2[1][:,1:3,:].clone()),dim=1)
well_target_pt_2 = well_list_target_2.clone()

assert well_y_pt.shape[0] == well_target_pt.shape[0]

# ============================================================================
# R2-1: 计算效率指标 (Computational Efficiency Metrics)
# ============================================================================
class ComputationalEfficiencyTracker:
    """
    跟踪模型推理的计算效率指标
    """
    def __init__(self, device):
        self.device = device
        self.inference_times = []
        self.memory_usage = []
        self.batch_sizes = []
        self.total_samples = 0

    def start_tracking(self):
        """开始跟踪"""
        if self.device.type == 'cuda':
            torch.cuda.synchronize()
            torch.cuda.reset_peak_memory_stats()
        self.start_time = time.time()
        self.start_memory = self._get_memory_usage()

    def end_tracking(self, batch_size):
        """结束跟踪"""
        if self.device.type == 'cuda':
            torch.cuda.synchronize()

        end_time = time.time()
        end_memory = self._get_memory_usage()

        inference_time = end_time - self.start_time
        memory_used = end_memory - self.start_memory

        self.inference_times.append(inference_time)
        self.memory_usage.append(memory_used)
        self.batch_sizes.append(batch_size)
        self.total_samples += batch_size

    def _get_memory_usage(self):
        """获取当前内存使用量 (MB)"""
        if self.device.type == 'cuda':
            return torch.cuda.memory_allocated(self.device) / (1024 ** 2)
        else:
            import psutil
            return psutil.Process().memory_info().rss / (1024 ** 2)

    def get_peak_memory(self):
        """获取峰值内存使用量 (MB)"""
        if self.device.type == 'cuda':
            return torch.cuda.max_memory_allocated(self.device) / (1024 ** 2)
        else:
            return max(self.memory_usage) if self.memory_usage else 0

    def report(self):
        """生成效率报告"""
        total_time = sum(self.inference_times)
        avg_time_per_batch = np.mean(self.inference_times) if self.inference_times else 0
        avg_time_per_sample = total_time / self.total_samples if self.total_samples > 0 else 0
        throughput = self.total_samples / total_time if total_time > 0 else 0

        print("\n" + "="*60)
        print("R2-1: 计算效率指标报告")
        print("="*60)
        print(f"设备: {self.device}")
        print(f"总推理样本数: {self.total_samples}")
        print(f"总推理时间: {total_time:.4f} 秒")
        print(f"平均每批次时间: {avg_time_per_batch*1000:.2f} 毫秒")
        print(f"平均每样本时间: {avg_time_per_sample*1000:.4f} 毫秒")
        print(f"吞吐量: {throughput:.2f} 样本/秒")
        print(f"峰值内存使用: {self.get_peak_memory():.2f} MB")

        if self.device.type == 'cuda':
            print(f"GPU: {torch.cuda.get_device_name(self.device)}")
            print(f"GPU总内存: {torch.cuda.get_device_properties(self.device).total_memory / (1024**3):.2f} GB")

        return {
            'total_samples': self.total_samples,
            'total_time_sec': total_time,
            'avg_time_per_batch_ms': avg_time_per_batch * 1000,
            'avg_time_per_sample_ms': avg_time_per_sample * 1000,
            'throughput_samples_per_sec': throughput,
            'peak_memory_mb': self.get_peak_memory()
        }

# ============================================================================
# R1-9: 特征重要性分析 (Feature Importance Analysis)
# ============================================================================
def compute_gradient_importance(model, input_data, target_idx=0, device='cuda'):
    """
    使用梯度分析计算特征重要性

    Args:
        model: 训练好的模型
        input_data: 输入数据 (N, C, L)
        target_idx: 目标输出的索引
        device: 计算设备

    Returns:
        importance: 每个输入特征的重要性分数
    """
    model.eval()
    input_tensor = input_data.clone().requires_grad_(True).to(device)

    # 创建Data对象
    data_obj = Data(input_sam=input_tensor, label=None)
    data_obj.x = input_tensor

    # 前向传播
    output = model(data_obj)

    # 对目标输出求和并反向传播
    target_output = output[:, target_idx, :].sum()
    target_output.backward()

    # 计算梯度的绝对值平均作为重要性
    gradients = input_tensor.grad.abs()
    importance = gradients.mean(dim=(0, 2))  # 对样本和序列长度维度求平均

    return importance.cpu().numpy()

def compute_permutation_importance(model, input_data, target_data, feature_names,
                                    n_repeats=5, device='cuda', batch_size=2):
    """
    使用排列重要性计算特征重要性

    Args:
        model: 训练好的模型
        input_data: 输入数据 (N, C, L)
        target_data: 目标数据 (N, C_out, L)
        feature_names: 特征名称列表
        n_repeats: 重复次数
        device: 计算设备
        batch_size: 批处理大小，默认2

    Returns:
        importance_df: 特征重要性 DataFrame
    """
    model.eval()

    # 计算基准MSE - 使用批处理
    with torch.no_grad():
        baseline_preds = []
        for i in range(0, input_data.shape[0], batch_size):
            batch_input = input_data[i:i+batch_size].to(device)
            data_obj = Data(input_sam=batch_input, label=None)
            data_obj.x = batch_input
            batch_pred = model(data_obj)
            # 移除CALI通道（索引0），只保留RSHA, RMED, RDEP, SP
            batch_pred = batch_pred[:, 1:, :]  # 从 (N, 5, L) 变为 (N, 4, L)
            baseline_preds.append(batch_pred.cpu())

        baseline_pred = torch.cat(baseline_preds, dim=0)

        # 确保维度匹配
        if baseline_pred.shape[0] != target_data.shape[0]:
            # 只对齐样本数量维度
            min_samples = min(baseline_pred.shape[0], target_data.shape[0])
            baseline_pred = baseline_pred[:min_samples]
            target_aligned = target_data[:min_samples]
        else:
            target_aligned = target_data

        # 确保 target_aligned 也在 CPU 上，与 baseline_pred 保持一致
        target_aligned = target_aligned.cpu()

        baseline_mse = F.mse_loss(baseline_pred, target_aligned).item()

    importance_scores = {name: [] for name in feature_names}

    for feat_idx, feat_name in enumerate(feature_names):
        for _ in range(n_repeats):
            # 创建打乱后的输入
            shuffled_input = input_data.clone()
            perm = torch.randperm(shuffled_input.shape[0])
            shuffled_input[:, feat_idx, :] = shuffled_input[perm, feat_idx, :]

            # 计算打乱后的MSE - 使用批处理
            with torch.no_grad():
                shuffled_preds = []
                for i in range(0, shuffled_input.shape[0], batch_size):
                    batch_shuffled = shuffled_input[i:i+batch_size].to(device)
                    data_obj = Data(input_sam=batch_shuffled, label=None)
                    data_obj.x = batch_shuffled
                    batch_pred = model(data_obj)
                    # 移除CALI通道（索引0），只保留RSHA, RMED, RDEP, SP
                    batch_pred = batch_pred[:, 1:, :]  # 从 (N, 5, L) 变为 (N, 4, L)
                    shuffled_preds.append(batch_pred.cpu())

                shuffled_pred = torch.cat(shuffled_preds, dim=0)
                shuffled_mse = F.mse_loss(shuffled_pred, target_aligned).item()

            # 重要性 = MSE增加量
            importance = shuffled_mse - baseline_mse
            importance_scores[feat_name].append(importance)

    # 创建结果DataFrame
    results = []
    for feat_name in feature_names:
        scores = importance_scores[feat_name]
        results.append({
            'Feature': feat_name,
            'Importance_Mean': np.mean(scores),
            'Importance_Std': np.std(scores),
            'Importance_Min': np.min(scores),
            'Importance_Max': np.max(scores)
        })

    importance_df = pd.DataFrame(results).sort_values('Importance_Mean', ascending=False)
    return importance_df, baseline_mse

def plot_feature_importance(importance_df, title="Feature Importance", save_path=None):
    """
    绘制特征重要性图

    Args:
        importance_df: 特征重要性 DataFrame
        title: 图表标题
        save_path: 保存路径
    """
    fig, ax = plt.subplots(figsize=(10, 6))

    features = importance_df['Feature'].values
    means = importance_df['Importance_Mean'].values
    stds = importance_df['Importance_Std'].values

    colors = plt.cm.RdYlGn_r(np.linspace(0.2, 0.8, len(features)))

    bars = ax.barh(features, means, xerr=stds, capsize=5, color=colors, edgecolor='black')

    ax.set_xlabel('Importance (MSE Increase)', fontsize=12)
    ax.set_ylabel('Feature', fontsize=12)
    ax.set_title(title, fontsize=14)
    ax.grid(True, alpha=0.3, axis='x')

    # 添加数值标签
    for bar, mean, std in zip(bars, means, stds):
        ax.text(mean + std + 0.001, bar.get_y() + bar.get_height()/2,
                f'{mean:.4f}', va='center', fontsize=9)

    plt.tight_layout()

    if save_path:
        plt.savefig(save_path, dpi=300, bbox_inches='tight')
        print(f"特征重要性图已保存至: {save_path}")

    plt.show()

# ============================================================================
# R2-3: 逆变换工作流程 (Inverse Transform Workflow)
# ============================================================================
class InverseTransformer:
    """
    反标准化工具类，将预测值转换回原始量级
    """
    def __init__(self, standard_data_path=None):
        """
        Args:
            standard_data_path: 标准化参数文件路径
        """
        self.group_stats = {}  # 存储组标准化参数
        self.global_stats = {}  # 存储全局标准化参数

        if standard_data_path:
            self.load_standard_params(standard_data_path)

    def load_standard_params(self, path):
        """加载标准化参数"""
        standard_data = pd.read_csv(path)
        for col in standard_data.columns:
            if col != 'WELL':
                self.global_stats[col] = {
                    'mean': standard_data[col].mean(),
                    'std': standard_data[col].std()
                }
        print(f"已加载标准化参数: {list(self.global_stats.keys())}")

    def set_feature_stats(self, feature_name, mean, std):
        """手动设置特征的标准化参数"""
        self.global_stats[feature_name] = {'mean': mean, 'std': std}

    def inverse_transform(self, data, feature_name):
        """
        反标准化单个特征

        Args:
            data: 标准化后的数据 (tensor 或 numpy array)
            feature_name: 特征名称

        Returns:
            反标准化后的数据
        """
        if feature_name not in self.global_stats:
            print(f"警告: 未找到 {feature_name} 的标准化参数，返回原始数据")
            return data

        mean = self.global_stats[feature_name]['mean']
        std = self.global_stats[feature_name]['std']

        if isinstance(data, torch.Tensor):
            return data * std + mean
        else:
            return data * std + mean

    def inverse_transform_batch(self, data, feature_names):
        """
        批量反标准化多个特征

        Args:
            data: 标准化后的数据 (N, C, L) 或 (C, L)
            feature_names: 特征名称列表

        Returns:
            反标准化后的数据
        """
        if isinstance(data, torch.Tensor):
            result = data.clone()
        else:
            result = data.copy()

        for i, name in enumerate(feature_names):
            if len(data.shape) == 3:
                result[:, i, :] = self.inverse_transform(data[:, i, :], name)
            elif len(data.shape) == 2:
                result[i, :] = self.inverse_transform(data[i, :], name)

        return result

    def report_transform_stats(self, original, transformed, feature_names):
        """
        报告原始数据和反标准化数据的统计信息对比
        """
        print("\n" + "="*60)
        print("R2-3: 逆变换统计对比")
        print("="*60)
        print(f"{'Feature':<15} {'Original Mean':<15} {'Transformed Mean':<15} {'Original Std':<15} {'Transformed Std':<15}")
        print("-"*75)

        for i, name in enumerate(feature_names):
            if len(original.shape) == 3:
                orig_data = original[:, i, :].flatten()
                trans_data = transformed[:, i, :].flatten()
            else:
                orig_data = original[i, :].flatten()
                trans_data = transformed[i, :].flatten()

            if isinstance(orig_data, torch.Tensor):
                orig_data = orig_data.cpu().numpy()
                trans_data = trans_data.cpu().numpy()

            print(f"{name:<15} {np.mean(orig_data):<15.4f} {np.mean(trans_data):<15.4f} "
                  f"{np.std(orig_data):<15.4f} {np.std(trans_data):<15.4f}")

# ============================================================================
# R2-4: 统计显著性测试 (Statistical Significance Testing)
# ============================================================================
def compute_metrics_per_well(predictions, targets, well_indices=None):
    """
    计算每口井的评估指标

    Args:
        predictions: 预测值 (N, C, L) 或 list of tensors
        targets: 目标值 (N, C, L) 或 list of tensors
        well_indices: 井的索引列表，用于分割数据

    Returns:
        metrics_df: 每口井的指标 DataFrame
    """
    if isinstance(predictions, torch.Tensor):
        predictions = predictions.cpu().numpy()
    if isinstance(targets, torch.Tensor):
        targets = targets.cpu().numpy()

    # 如果是3D数据，展平
    if len(predictions.shape) == 3:
        N, C, L = predictions.shape
        predictions = predictions.reshape(N, -1)
        targets = targets.reshape(N, -1)

    metrics_list = []

    if well_indices is None:
        # 如果没有井索引，将整个数据作为一口井
        well_indices = [(0, len(predictions))]

    for well_id, (start, end) in enumerate(well_indices):
        pred = predictions[start:end].flatten()
        targ = targets[start:end].flatten()

        # 计算各种指标
        mse = np.mean((pred - targ) ** 2)
        rmse = np.sqrt(mse)
        mae = np.mean(np.abs(pred - targ))

        # R² (决定系数)
        ss_res = np.sum((targ - pred) ** 2)
        ss_tot = np.sum((targ - np.mean(targ)) ** 2)
        r2 = 1 - (ss_res / ss_tot) if ss_tot > 0 else 0

        # Pearson 相关系数
        if np.std(pred) > 0 and np.std(targ) > 0:
            pearson_r, pearson_p = stats.pearsonr(pred, targ)
        else:
            pearson_r, pearson_p = 0, 1

        metrics_list.append({
            'Well_ID': well_id,
            'MSE': mse,
            'RMSE': rmse,
            'MAE': mae,
            'R2': r2,
            'Pearson_R': pearson_r,
            'Pearson_P': pearson_p,
            'N_Samples': end - start
        })

    return pd.DataFrame(metrics_list)

def statistical_significance_report(metrics_df, sample_level_mse_df=None, save_path=None):
    """
    生成统计显著性报告（R2-4）- 支持样本级配对检验

    Args:
        metrics_df: 每口井的汇总指标 DataFrame（FNPG模型）
        sample_level_mse_df: 样本级MSE DataFrame，包含列['Well_ID', 'Sample_ID', 'MSE']
        save_path: 保存路径

    Returns:
        summary: 汇总统计信息
    """
    print("\n" + "="*70)
    print("R2-4: 统计显著性测试报告（样本级配对检验）")
    print("="*70)

    # Baseline模型的样本级MSE数据
    # Baseline模型的样本级MSE数据（从baseline_inference_for_r2_4.py获取）
    # 格式：每个模型包含一个与FNPG样本对应的MSE列表（66个样本）
    baseline_sample_mse = {
        'ResNet': np.array([0.98706925, 0.9366053, 0.9702574, 0.920876, 0.9651431, 0.9771453, 0.9059391, 1.005785, 0.9903662, 0.93761265, 0.9871123, 0.9393952, 0.9760841, 0.97867227, 0.9347437, 0.94324803, 0.9636047, 0.96508825, 0.9875119, 0.9620669, 0.95160514, 0.9651338, 0.95695364, 0.98367727, 0.9670499, 0.9275438, 0.9801244, 0.99611026, 0.94583374, 0.96602833, 0.96725345, 0.95934594, 0.9326618, 0.9117849, 0.82115096, 0.786203, 0.8303516, 0.76386297, 0.8351867, 0.5705767, 0.796871, 0.7831533, 0.98534787, 0.9790696, 0.9123082, 0.94682103, 0.9368639, 0.9460222, 0.8980199, 0.9252275, 0.948563, 0.9461317, 0.9558, 0.9669614, 0.9589281, 0.9421855, 0.9566839, 0.9606283, 0.9914578, 0.9284284, 0.9672307, 0.9621857, 0.8761652, 0.95914584, 0.8625606, 0.9096527]),
        'Bi-LSTM': np.array([0.77756697, 0.9589925, 0.7408166, 0.50958145, 0.6211033, 0.87214303, 0.6692221, 0.82510674, 0.71200866, 0.94580173, 0.66032386, 0.671936, 1.5358099, 0.39258027, 0.61162746, 0.81775266, 0.8911872, 0.74834704, 0.8185557, 0.88765466, 0.69681466, 0.77060235, 0.43772003, 0.49088192, 0.44029295, 0.42148978, 0.4199715, 0.44700074, 0.8034998, 0.62744176, 0.7164782, 0.6274303, 0.76366127, 0.6900452, 0.7056626, 0.41290057, 0.50397635, 0.73077095, 0.44967246, 0.41078898, 0.5826504, 0.4553375, 0.9049238, 1.2960627, 0.92917067, 0.90750146, 0.91014063, 0.72206885, 0.8093785, 0.8530593, 0.68073153, 0.9561082, 0.9648535, 0.5455279, 0.5029714, 0.6998795, 0.98627865, 0.6071861, 0.53034353, 0.97406614, 0.4687064, 0.71462274, 0.8488518, 1.0118817, 0.6153976, 0.65960515])
    }

    # 计算汇总统计
    summary = {}
    metrics_to_summarize = ['MSE', 'RMSE', 'MAE', 'R2', 'Pearson_R']

    print("\n各井评估指标 (FNPG):")
    print(metrics_df.to_string(index=False))

    print("\n" + "-"*70)
    print("汇总统计 (均值 ± 标准差):")
    print("-"*70)
    print(f"{'Metric':<15} {'Mean':<12} {'Std':<12} {'Min':<12} {'Max':<12} {'95% CI':<20}")
    print("-"*70)

    for metric in metrics_to_summarize:
        values = metrics_df[metric].values
        mean = np.mean(values)
        std = np.std(values)
        min_val = np.min(values)
        max_val = np.max(values)

        # 95% 置信区间
        n = len(values)
        ci = 1.96 * std / np.sqrt(n) if n > 1 else 0
        ci_lower = mean - ci
        ci_upper = mean + ci

        summary[metric] = {
            'mean': mean,
            'std': std,
            'min': min_val,
            'max': max_val,
            'ci_95_lower': ci_lower,
            'ci_95_upper': ci_upper
        }

        print(f"{metric:<15} {mean:<12.4f} {std:<12.4f} {min_val:<12.4f} {max_val:<12.4f} [{ci_lower:.4f}, {ci_upper:.4f}]")

    # 假设检验
    print("\n" + "-"*70)
    print("假设检验:")
    print("-"*70)

    # 1. 单样本 t 检验（检验 R² 是否显著大于 0）
    r2_values = metrics_df['R2'].values[:2]  # 只使用前两口井
    if len(r2_values) > 1:
        t_stat, p_value = stats.ttest_1samp(r2_values, 0)
        print(f"\n1) R² > 0 单样本 t 检验: t = {t_stat:.4f}, p = {p_value:.6f}")
        if p_value < 0.05:
            print("   → 结论: R² 显著大于 0 (p < 0.05)")
        else:
            print("   → 结论: R² 与 0 无显著差异 (p >= 0.05)")

    # 2. 样本级配对 t 检验（FNPG vs. Baseline模型）
    print(f"\n2) 样本级配对 t 检验 (FNPG vs. Baseline模型):")

    if sample_level_mse_df is not None:
        # 提取FNPG的样本级MSE（只使用前两口井）
        fnpg_sample_mse = sample_level_mse_df[sample_level_mse_df['Well_ID'].isin([0, 1])]['MSE'].values
        n_samples = len(fnpg_sample_mse)
        print(f"   样本数量: n = {n_samples}")
        print(f"   FNPG样本级MSE: 均值={np.mean(fnpg_sample_mse):.4f}, 标准差={np.std(fnpg_sample_mse):.4f}")

        # 对每个baseline模型进行配对检验
        for model_name, baseline_mse_array in baseline_sample_mse.items():
            if baseline_mse_array is not None:
                baseline_mse_array = np.array(baseline_mse_array)

                if len(baseline_mse_array) == n_samples:
                    # 配对 t 检验
                    t_stat, p_value = stats.ttest_rel(fnpg_sample_mse, baseline_mse_array)

                    # 计算效应量 (Cohen's d for paired samples)
                    diff = fnpg_sample_mse - baseline_mse_array
                    cohens_d = np.mean(diff) / np.std(diff, ddof=1)

                    # 计算改进百分比
                    improvement = (np.mean(baseline_mse_array) - np.mean(fnpg_sample_mse)) / np.mean(baseline_mse_array) * 100

                    print(f"\n   FNPG vs. {model_name}:")
                    print(f"     FNPG MSE:      均值={np.mean(fnpg_sample_mse):.4f}, 标准差={np.std(fnpg_sample_mse):.4f}")
                    print(f"     {model_name} MSE:   均值={np.mean(baseline_mse_array):.4f}, 标准差={np.std(baseline_mse_array):.4f}")
                    print(f"     配对 t 检验:   t = {t_stat:.4f}, p = {p_value:.6f}")
                    print(f"     效应量 (Cohen's d): {cohens_d:.4f}")
                    print(f"     MSE改进:       {improvement:.2f}%")

                    if p_value < 0.05:
                        if t_stat < 0:
                            print(f"     → 结论: FNPG显著优于{model_name} (p < 0.05) ✓✓✓")
                        else:
                            print(f"     → 结论: FNPG显著劣于{model_name} (p < 0.05)")
                    else:
                        print(f"     → 结论: FNPG与{model_name}无显著差异 (p >= 0.05)")
                else:
                    print(f"\n   警告: {model_name}的样本数({len(baseline_mse_array)})与FNPG不匹配({n_samples})")
            else:
                print(f"\n   提示: {model_name}的baseline数据未提供，跳过配对检验")

        print(f"\n   优势: 样本级配对检验(n={n_samples})比井级检验(n=2)具有更高的统计功效")
    else:
        print("   警告: 未提供样本级MSE数据，无法进行样本级配对检验")

    # 可视化
    fig = plt.figure(figsize=(16, 10))
    gs = fig.add_gridspec(2, 3, hspace=0.3, wspace=0.3)

    # 只使用前两口井的数据进行可视化（排除异常的第三口井）
    valid_wells = metrics_df.iloc[:2]

    # 1. MSE 分布（带误差棒）
    ax1 = fig.add_subplot(gs[0, 0])
    mse_values = valid_wells['MSE'].values
    mse_mean = np.mean(mse_values)
    mse_std = np.std(mse_values)
    mse_ci = 1.96 * mse_std / np.sqrt(len(mse_values))  # 95% CI

    ax1.bar(valid_wells['Well_ID'], mse_values, color='steelblue', edgecolor='black', alpha=0.7)
    ax1.errorbar(valid_wells['Well_ID'], mse_values, yerr=mse_ci, fmt='none',
                 ecolor='red', capsize=5, capthick=2, label='95% CI')
    ax1.axhline(y=mse_mean, color='red', linestyle='--', linewidth=2, label=f'Mean={mse_mean:.4f}')
    ax1.set_xlabel('Well ID', fontsize=11)
    ax1.set_ylabel('MSE', fontsize=11)
    ax1.set_title('MSE per Well (with 95% CI)', fontsize=12, fontweight='bold')
    ax1.set_xticks([0, 1])  # 设置整数刻度
    ax1.legend(fontsize=9)
    ax1.grid(True, alpha=0.3)

    # 2. R² 分布（带误差棒）
    ax2 = fig.add_subplot(gs[0, 1])
    r2_values = valid_wells['R2'].values
    r2_mean = np.mean(r2_values)
    r2_std = np.std(r2_values)
    r2_ci = 1.96 * r2_std / np.sqrt(len(r2_values))  # 95% CI

    ax2.bar(valid_wells['Well_ID'], r2_values, color='forestgreen', edgecolor='black', alpha=0.7)
    ax2.errorbar(valid_wells['Well_ID'], r2_values, yerr=r2_ci, fmt='none',
                 ecolor='red', capsize=5, capthick=2, label='95% CI')
    ax2.axhline(y=r2_mean, color='red', linestyle='--', linewidth=2, label=f'Mean={r2_mean:.4f}')
    ax2.set_xlabel('Well ID', fontsize=11)
    ax2.set_ylabel('R²', fontsize=11)
    ax2.set_title('R² per Well (with 95% CI)', fontsize=12, fontweight='bold')
    ax2.set_xticks([0, 1])  # 设置整数刻度
    ax2.legend(fontsize=9)
    ax2.grid(True, alpha=0.3)

    # 3. FNPG vs. Baseline 对比图（样本级MSE均值）
    ax3 = fig.add_subplot(gs[0, 2])

    # 计算FNPG的平均MSE
    if sample_level_mse_df is not None:
        fnpg_mean_mse = np.mean(sample_level_mse_df[sample_level_mse_df['Well_ID'].isin([0, 1])]['MSE'].values)
    else:
        fnpg_mean_mse = np.mean(valid_wells['MSE'].values)

    # 收集有数据的baseline模型
    available_models = ['FNPG']
    available_mses = [fnpg_mean_mse]

    for model_name, baseline_mse_array in baseline_sample_mse.items():
        if baseline_mse_array is not None:
            available_models.append(model_name)
            available_mses.append(np.mean(baseline_mse_array))

    if len(available_models) > 1:
        x_pos = np.arange(len(available_models))
        colors_bar = ['steelblue'] + ['lightcoral'] * (len(available_models) - 1)
        bars = ax3.bar(x_pos, available_mses, color=colors_bar, edgecolor='black', alpha=0.7)

        # 标注数值
        for bar, mse in zip(bars, available_mses):
            height = bar.get_height()
            ax3.text(bar.get_x() + bar.get_width()/2., height,
                    f'{mse:.4f}', ha='center', va='bottom', fontsize=9)

        ax3.set_xticks(x_pos)
        ax3.set_xticklabels(available_models, rotation=15, ha='right', fontsize=10)
        ax3.set_ylabel('Mean MSE (Sample-Level)', fontsize=11)
        ax3.set_title('FNPG vs. Baseline Models', fontsize=12, fontweight='bold')
        ax3.grid(True, alpha=0.3, axis='y')
    else:
        # 如果没有baseline数据，只显示FNPG
        ax3.bar([0], [fnpg_mean_mse], color='steelblue', edgecolor='black', alpha=0.7)
        ax3.text(0, fnpg_mean_mse, f'{fnpg_mean_mse:.4f}', ha='center', va='bottom', fontsize=9)
        ax3.set_xticks([0])
        ax3.set_xticklabels(['FNPG'], fontsize=10)
        ax3.set_ylabel('Mean MSE (Sample-Level)', fontsize=11)
        ax3.set_title('FNPG Performance (No Baseline Data)', fontsize=12, fontweight='bold')
        ax3.grid(True, alpha=0.3, axis='y')

    # 4. 误差指标对比图（改用bar plot，因为只有2口井）
    ax4 = fig.add_subplot(gs[1, 0])
    metrics_names = ['MSE', 'RMSE', 'MAE']
    metrics_means = [valid_wells['MSE'].mean(), valid_wells['RMSE'].mean(), valid_wells['MAE'].mean()]
    metrics_stds = [valid_wells['MSE'].std(), valid_wells['RMSE'].std(), valid_wells['MAE'].std()]

    x_pos = np.arange(len(metrics_names))
    colors = ['lightblue', 'lightgreen', 'lightyellow']
    bars = ax4.bar(x_pos, metrics_means, color=colors, edgecolor='black', alpha=0.7)
    ax4.errorbar(x_pos, metrics_means, yerr=metrics_stds, fmt='none',
                 ecolor='red', capsize=5, capthick=2, label='Std Dev')

    # 标注数值
    for i, (bar, mean, std) in enumerate(zip(bars, metrics_means, metrics_stds)):
        ax4.text(bar.get_x() + bar.get_width()/2., mean + std + 0.01,
                f'{mean:.4f}', ha='center', va='bottom', fontsize=9)

    ax4.set_xticks(x_pos)
    ax4.set_xticklabels(metrics_names)
    ax4.set_ylabel('Value', fontsize=11)
    ax4.set_title('Error Metrics (Mean ± Std)', fontsize=12, fontweight='bold')
    ax4.legend(fontsize=9)
    ax4.grid(True, alpha=0.3, axis='y')

    # 5. Pearson相关系数分布
    ax5 = fig.add_subplot(gs[1, 1])
    pearson_values = valid_wells['Pearson_R'].values
    pearson_mean = np.mean(pearson_values)
    pearson_std = np.std(pearson_values)
    pearson_ci = 1.96 * pearson_std / np.sqrt(len(pearson_values))

    ax5.bar(valid_wells['Well_ID'], pearson_values, color='coral', edgecolor='black', alpha=0.7)
    ax5.errorbar(valid_wells['Well_ID'], pearson_values, yerr=pearson_ci, fmt='none',
                 ecolor='red', capsize=5, capthick=2, label='95% CI')
    ax5.axhline(y=pearson_mean, color='red', linestyle='--', linewidth=2, label=f'Mean={pearson_mean:.4f}')
    ax5.set_xlabel('Well ID', fontsize=11)
    ax5.set_ylabel('Pearson R', fontsize=11)
    ax5.set_title('Pearson Correlation per Well', fontsize=12, fontweight='bold')
    ax5.set_xticks([0, 1])  # 设置整数刻度
    ax5.legend(fontsize=9)
    ax5.grid(True, alpha=0.3)

    # 6. 样本数量分布
    ax6 = fig.add_subplot(gs[1, 2])
    ax6.bar(valid_wells['Well_ID'], valid_wells['N_Samples'], color='mediumpurple', edgecolor='black', alpha=0.7)
    for i, (well_id, n_samples) in enumerate(zip(valid_wells['Well_ID'], valid_wells['N_Samples'])):
        ax6.text(well_id, n_samples, f'{n_samples}', ha='center', va='bottom', fontsize=10, fontweight='bold')
    ax6.set_xlabel('Well ID', fontsize=11)
    ax6.set_ylabel('Number of Samples', fontsize=11)
    ax6.set_title('Sample Size per Well', fontsize=12, fontweight='bold')
    ax6.set_xticks([0, 1])  # 设置整数刻度
    ax6.grid(True, alpha=0.3, axis='y')


    plt.suptitle('Statistical Significance Analysis (R2-4)', fontsize=14)
    plt.tight_layout()

    if save_path:
        plt.savefig(save_path, dpi=300, bbox_inches='tight')
        print(f"\n统计显著性图已保存至: {save_path}")

    plt.show()

    return summary

# ============================================================================
# 初始化效率追踪器
# ============================================================================
efficiency_tracker = ComputationalEfficiencyTracker(device)

infer_dataset = my_dataset(well_y_pt, well_target_pt) #输入值，标签值
from torch.utils.data import DataLoader
# 使用标准的 PyTorch DataLoader
infer_loader = DataLoader(
    infer_dataset,
    batch_size=2,#2
    num_workers=0,
    shuffle=False,
    drop_last=True,
    collate_fn=custom_collate  # 使用自定义的collate_fn
)
import torch.optim as optim
# 使用 kmax=32 的模型
model = FNPG(args.graph_channels,2,args.fea_litho,args.head,args.drop,modes1=32).to(device)

criterion = CustomLossWithAdaptiveDerivativePenaltyAndWavelet()
optimizer = optim.Adam(list(model.parameters())+list(criterion.parameters()), lr=0.001, weight_decay=1e-4)

STAGE = 'GCRR_GRSB'
# 使用 kmax_32 的模型路径
filename = '/content/drive/MyDrive/logcompletion/model/kmax_sensitivity/kmax_32/FNPG_kmax32_best.pt'
# 读取最好的模型
model, optimizer, best_epoch, best_loss = load_best_model(model, optimizer, filename)
print(f"已加载模型 (epoch {best_epoch}, val_loss={best_loss:.6f})")

# ============================================================================
# 执行推理 (带效率追踪)
# ============================================================================
print("\n" + "="*60)
print("开始模型推理...")
print("="*60)

model.eval()
out_list = []

# R2-1: 开始总体效率追踪
total_start_time = time.time()

for batch_idx, i in enumerate(infer_loader):
    i.x = i.x.view(-1, 4, 512)
    batch_size = i.x.shape[0]

    # R2-1: 记录每个批次的效率
    efficiency_tracker.start_tracking()

    with torch.no_grad():
        output = model(i)

    efficiency_tracker.end_tracking(batch_size)

    out_list.append(output)

total_inference_time = time.time() - total_start_time
print(f"推理完成！总耗时: {total_inference_time:.4f} 秒")

# R2-1: 生成效率报告
efficiency_metrics = efficiency_tracker.report()

out_list = torch.cat(out_list, dim=0)
# 链式写法针对一个预测曲线
#out_list = out_list.unsqueeze(1)
# out_list:(32,5,512) 包含5个输出通道：CALI, RSHA, RMED, RDEP, SP
print(out_list.shape)

# 移除CALI通道（索引0），只保留RSHA, RMED, RDEP, SP
print("移除CALI通道前的形状:", out_list.shape)
out_list = out_list[:, 1:, :]  # 从 (N, 5, 512) 变为 (N, 4, 512)
print("移除CALI通道后的形状:", out_list.shape)

# 注意：well_target_pt 在定义时（1198行）已经移除了CALI，无需再次移除

# 将它整井的长度放在最后一维
out_list = out_list.permute(1,0,2).reshape(-1,out_list.size(0)*out_list.size(2))
well_target_pt = well_target_pt.permute(1,0,2).reshape(-1,well_target_pt.size(0)*well_target_pt.size(2))
well_y_pt = well_y_pt.permute(1,0,2).reshape(-1,well_y_pt.size(0)*well_y_pt.size(2))
well_x_pt = well_x_pt.permute(1,0,2).reshape(-1,well_x_pt.size(0)*well_x_pt.size(2))
print(well_y_pt.shape)
print(well_x_pt.shape)

#15.9-15
well_name = '15/9-15'
single_well = train_ori_set_2[train_ori_set_2['WELL'] == f'{well_name}'].copy()
assert single_well.shape[0] != 0, "single_well is empty"
# 移除CALI，只保留RSHA, RMED, RDEP, SP
selected = single_well[['RSHA', 'RMED',  'RDEP', 'SP']].copy()
print(f'{well_name}元数据长度为',selected.shape)
selected = selected.reset_index(drop=True).values.tolist()#注意，滑动截取的井数据index都会reset，回想自己之前写的算法
"""
15/9-15井的元数据长度为17717，well_target_pt是512窗口滑动的该井数据，长度为17,408 二者相差309
"""
selected = torch.tensor(selected).transpose(0, 1)
## 在15.9-15井中选取GR,NPHI,RHOB和DTC，画Missing reconstruction部分
selected_4rc = single_well[['GR','NPHI','RHOB','DTC']].copy()#for reconstruction
print(f'{well_name}用于重建的元数据长度为',selected_4rc.shape)
selected_4rc = selected_4rc.reset_index(drop=True).values.tolist()
selected_4rc = torch.tensor(selected_4rc).transpose(0, 1)

#15.9-17
well_name = '15/9-17'
single_well = train_ori_set_2[train_ori_set_2['WELL'] == f'{well_name}'].copy()
assert single_well.shape[0] != 0, "single_well is empty"
# 移除CALI，只保留RSHA, RMED, RDEP, SP
selected = single_well[['RSHA', 'RMED',  'RDEP', 'SP']].copy()
print(f'{well_name}元数据长度为',selected.shape)
selected = selected.reset_index(drop=True).values.tolist()#注意，滑动截取的井数据index都会reset，回想自己之前写的算法
"""
15/9-17井的元数据长度为17350，well_target_pt是512窗口滑动的该井数据，长度为16,384 二者相差966
"""
selected = torch.tensor(selected).transpose(0, 1)

## 在15.9-17井中选取GR,NPHI,RHOB和DTC，画Missing reconstruction部分
selected_4rc = single_well[['GR','NPHI','RHOB','DTC']].copy()#for reconstruction
print(f'{well_name}用于重建的元数据长度为',selected_4rc.shape)
selected_4rc = selected_4rc.reset_index(drop=True).values.tolist()
selected_4rc = torch.tensor(selected_4rc).transpose(0, 1)

print(well_target_pt.shape)
print(well_y_pt.shape)
print(out_list.shape)
print(selected.shape)
print(selected_4rc.shape)

# 裁剪到所有数据中的最小长度，确保维度匹配
min_len = min(selected.shape[1], well_target_pt.shape[1], out_list.shape[1])
selected = selected[:, :min_len]
selected_4rc = selected_4rc[:, :min_len]
well_target_pt = well_target_pt[:, :min_len]
well_y_pt = well_y_pt[:, :min_len]
out_list = out_list[:, :min_len]

print(f"裁剪后统一长度: {min_len}")

# 使用 torch.nan_to_num() 将 NaN 值替换为 5.0
selected_filled = torch.nan_to_num(selected, nan=5.0)
print(selected_filled.shape)

# 避免上下i变量名的混淆
i = 0

# Make predictions on train_loader
with torch.no_grad():
    a = next(iter(infer_loader))
    # 动态计算实际批次大小，避免硬编码导致的形状不匹配
    actual_batch_size = a.x.numel() // (len(args.fea_litho) * args.sam_len)
    a.x = a.x.view(actual_batch_size, len(args.fea_litho), args.sam_len)
    predictions = model(a)
    i+=1
    print(f'{i} iteration (batch_size={actual_batch_size})')

# 这一个cell写了两遍，第一遍
## 将预测值加上 meta与模型输入值的 差值
#target = selected_filled.detach().cpu().unsqueeze(0)
# selected_filled是原数据为了shape将NAN转换为5的
#target_plot = np.where(target[0, i, :] == 5, np.nan, target[0, i, :])
# 创建一个与target相同形状的全零数组
#mask_list = np.zeros_like(target, dtype=float)

# 将target中值为5的位置在mask_list中设为NaN，mask_list与well_target_pt.detach().cpu().unsqueeze(0)相加
#mask_list[target == 5] = np.nan

label = well_target_pt.detach().cpu().unsqueeze(0)#标准化的标签
#meta = selected_filled.detach().cpu().unsqueeze(0)#原数据meta,NAN值都化为5
# 使用 torch.nan_to_num 将 NaN 转换为 0
#meta = torch.nan_to_num(meta, nan=0.0)
input = well_y_pt.detach().cpu().unsqueeze(0)#模型输入值
predict = out_list.detach().cpu().unsqueeze(0)#模型预测值

# out_list 因为drop_last=True,丢了一部分
#diff = meta - label
#predict_diffAdd = predict + diff

#print(predict_diffAdd.shape)
# 上去再跑另一个井

# 这一个cell写了两遍，第二遍
## 将预测值加上 meta与模型输入值的 差值
target_2 = selected_filled.detach().cpu().unsqueeze(0)
# selected_filled是原数据为了shape将NAN转换为5的
target_plot = np.where(target_2[0, i, :] == 5, np.nan, target_2[0, i, :])
# 创建一个与target相同形状的全零数组
mask_list = np.zeros_like(target_2, dtype=float)

# 将target中值为5的位置在mask_list中设为NaN，mask_list与well_target_pt.detach().cpu().unsqueeze(0)相加
mask_list[target_2 == 5] = np.nan

label_2 = well_target_pt.detach().cpu().unsqueeze(0)#标准化的标签
meta_2 = selected_filled.detach().cpu().unsqueeze(0)#原数据meta,NAN值都化为5
# 使用 torch.nan_to_num 将 NaN 转换为 0
meta_2 = torch.nan_to_num(meta_2, nan=0.0)
input_2 = well_y_pt.detach().cpu().unsqueeze(0)#模型输入值
predict_2 = out_list.detach().cpu().unsqueeze(0)#模型预测值

# out_list 因为drop_last=True,丢了一部分
diff_2 = meta_2 - label_2
predict_diffAdd_2 = predict_2 + diff_2

print(predict_diffAdd_2.shape)

#@title Figure12
# Visualize results
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from scipy import stats
def plot_results(data, predictions, target, log_names, depth, fig_size=(20, 24), dpi=300):
    """
    Plot the results of well log predictions in an academic style, leaving gaps for values equal to 5.

    Parameters:
    - data (numpy.ndarray): Input well log data of shape (n_samples, n_logs, depth)
    - predictions (numpy.ndarray): Predicted well log data of shape (n_samples, n_predicted_logs, depth)
    - target (numpy.ndarray): Actual target well log data of shape (n_samples, n_predicted_logs, depth)
    - log_names (list): List of names for input and predicted logs
    - depth (numpy.ndarray): Depth values for the well logs
    - fig_size (tuple): Figure size (width, height) in inches
    - dpi (int): Dots per inch for the figure

    Returns:
    - fig (matplotlib.figure.Figure): The created figure object
    """

    # Set the style for the plots
    sns.set_style("whitegrid")
    plt.rcParams['font.family'] = 'serif'
    plt.rcParams['font.serif'] = ['Times New Roman'] + plt.rcParams['font.serif']

    # Move tensors to CPU and convert to NumPy arrays
    data = data.cpu().numpy()
    n_input_logs = data.shape[1]

    if target is not None:
      predictions = predictions.cpu().numpy()
      target = target.cpu().numpy()

      n_predicted_logs = predictions.shape[1]

      # Create subplots
      fig, axs = plt.subplots(1, n_input_logs + n_predicted_logs + 1, figsize=fig_size, dpi=dpi, sharey=True)
      fig.suptitle("Well Log Prediction Results", fontsize=24, fontweight='bold')

      # Plot input logs
      for i in range(n_input_logs):
          axs[i].plot(data[0, i, :], depth, label='Actual', color='black', linewidth=0.5)
          axs[i].set_title(log_names[i], fontsize=16)
          axs[i].set_xlabel(log_names[i] + ' Value', fontsize=12)
          axs[i].invert_yaxis()
          axs[i].grid(True, which='both', linestyle='--', linewidth=0.5)
          axs[i].tick_params(axis='both', which='major', labelsize=10)

      # Plot predicted vs actual logs, leaving gaps for target values equal to 5
      for i in range(n_predicted_logs):

          predictions_plot = np.where(target[0, i, :] == 5, np.nan, predictions[0, i, :])#只给元数据赋值NAN，预测值保留以显示reconstrcution.

          axs[n_input_logs + i].plot(target[0, i, :], depth, label='Actual', color='black', linewidth=0.5)#这里的target是传入的target_plot
          axs[n_input_logs + i].plot(predictions[0, i, :], depth, label='Predicted', color='red', linewidth=0.5, linestyle='--')
          axs[n_input_logs + i].set_title(log_names[n_input_logs + i], fontsize=16)
          axs[n_input_logs + i].set_xlabel(log_names[n_input_logs + i] + ' Value', fontsize=12)
          axs[n_input_logs + i].legend(fontsize=10)
          axs[n_input_logs + i].grid(True, which='both', linestyle='--', linewidth=0.5)
          axs[n_input_logs + i].tick_params(axis='both', which='major', labelsize=10)

      # Set common y-label
      fig.text(0.04, 0.5, 'Depth (m)', va='center', rotation='vertical', fontsize=14)

      # Plot error distribution and cross-plot
      error = predictions[0, 0, :] - target[0, 0, :]
      ax_hist = axs[-1]
      sns.histplot(error, kde=True, ax=ax_hist)
      ax_hist.set_title('Error Distribution', fontsize=16)
      ax_hist.set_xlabel('Error', fontsize=12)
      ax_hist.set_ylabel('Frequency', fontsize=12)

      # Add statistical information to the error distribution plot
      mean_error = np.mean(error)
      std_error = np.std(error)
      rmse = np.sqrt(np.mean(error**2))
      r2 = stats.pearsonr(predictions[0, 0, :], target[0, 0, :])[0]**2

      stats_text = f'Mean: {mean_error:.2f}\nStd: {std_error:.2f}\nRMSE: {rmse:.2f}\nR²: {r2:.2f}'
      ax_hist.text(0.95, 0.95, stats_text, transform=ax_hist.transAxes, fontsize=10,
                  verticalalignment='top', horizontalalignment='right',
                  bbox=dict(boxstyle='round', facecolor='white', alpha=0.8))

      # Adjust layout and display the plot
      plt.tight_layout(rect=[0.05, 0.03, 1, 0.95])

      # Add a cross-plot as an inset axis in the error distribution subplot
      ax_cross = ax_hist.inset_axes([0.05, 0.6, 0.4, 0.35])
      ax_cross.scatter(target[0, 0, :], predictions[0, 0, :], alpha=0.5, s=1)
      ax_cross.set_xlabel('Actual', fontsize=8)
      ax_cross.set_ylabel('Predicted', fontsize=8)
      ax_cross.set_title('Cross-plot', fontsize=10)

      # Add a 45-degree reference line
      lims = [
          np.min([ax_cross.get_xlim(), ax_cross.get_ylim()]),
          np.max([ax_cross.get_xlim(), ax_cross.get_ylim()]),
      ]
      ax_cross.plot(lims, lims, 'r--', alpha=0.75, zorder=0)
      ax_cross.set_aspect('equal')
      ax_cross.tick_params(axis='both', which='major', labelsize=6)
    else:
      # Create subplots
      fig, axs = plt.subplots(1, n_input_logs, figsize=fig_size, dpi=dpi, sharey=True)
      fig.suptitle("Well Log Reconstruction Results", fontsize=24, fontweight='bold')

      # Plot input logs
      for i in range(n_input_logs):
          axs[i].plot(data[0, i, :], depth, label='Actual', color='black', linewidth=0.5)
          axs[i].plot(predictions[0, i, :], depth, label='Reconstruction', color='red', linewidth=0.5, linestyle='--')#这里的predictions变量是上一个IF定义中的data
          axs[i].set_title(log_names[i], fontsize=16)
          axs[i].set_xlabel(log_names[i] + ' Value', fontsize=12)
          axs[i].invert_yaxis()
          axs[i].grid(True, which='both', linestyle='--', linewidth=0.5)
          axs[i].tick_params(axis='both', which='major', labelsize=10)

      # Set common y-label
      fig.text(0.04, 0.5, 'Depth (m)', va='center', rotation='vertical', fontsize=14)

    return fig

# Example usage:
# Assuming you have the following variables:
# - data: input well log data
# - predictions: predicted well log data
# - target: actual target well log data
# - depth: depth values for the well logs

# 移除CALI，只保留输入特征和其他输出特征
log_names = ['GR', 'RHOB', 'NPHI', 'DTC', 'RSHA', 'RMED',  'RDEP', 'SP']
depth = np.arange(0, out_list.shape[-1]) #np.arange(0, 512)

print(input.shape, predict.shape, label.shape)
fig = plot_results(input, predict, label, log_names, depth)

#注意，15.9-15井没有NAN值，因此mask_list全是初始的-inf，进入plot_results函数会报错

#fig = plot_results(well_y_pt.detach().cpu().unsqueeze(0), predict_diffAdd,#predict
#                   label_2, log_names = ['GR', 'RHOB', 'NPHI', 'DTC',#+mask_list
#                  'CALI', 'RSHA', 'RMED',  'RDEP', 'SP'], depth=np.arange(0, out_list.shape[-1])) #well_target_pt

#fig = plot_results(well_y_pt.detach().cpu().unsqueeze(0), predict_diffAdd_2[:,:,:well_y_pt.shape[-1]],#out_list.detach().cpu().unsqueeze(0),
#                  selected_filled.detach().cpu().unsqueeze(0)+mask_list, log_names = log_names, depth=depth)

# Missing Reconstruction
#selected_4rc_ = selected_4rc.detach().cpu().unsqueeze(0)
#mask = torch.where(torch.isnan(selected_4rc_), selected_4rc_, torch.tensor(0.0))
#fig = plot_results(well_x_pt.detach().cpu().unsqueeze(0)+mask, well_y_pt.detach().cpu().unsqueeze(0), None, log_names, depth)
from datetime import datetime
# 获取当前时间并格式化为字符串
timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
filename = f"/content/drive/MyDrive/logcompletion/figure/15.9-15_缺失重建和模型预测及标签未标准化_矢量图{timestamp}.pdf"
#plt.savefig(filename, format='pdf', dpi=600, bbox_inches='tight')

#plt.close(fig)

# ============================================================================
# R1-9: 特征重要性分析
# ============================================================================
print("\n" + "="*70)
print("R1-9: 特征重要性分析")
print("="*70)

# 使用排列重要性方法
print("\n计算排列重要性 (Permutation Importance)...")
print("(这可能需要几分钟时间)")

# 准备输入和目标数据
input_for_importance = well_y_pt_original.clone() if 'well_y_pt_original' in dir() else tensor_list_y[0].clone()
target_for_importance = well_target_pt_original.clone() if 'well_target_pt_original' in dir() else well_list_target_.clone()

try:
    # 确保样本数是 batch_size 的倍数
    n_samples = 100
    batch_size = 2
    n_samples = (n_samples // batch_size) * batch_size  # 调整为100

    importance_df, baseline_mse = compute_permutation_importance(
        model,
        input_for_importance[:n_samples],  # 使用前100个样本加速计算
        target_for_importance[:n_samples],
        input_feature_names,
        n_repeats=3,
        device=device,
        batch_size=batch_size
    )

    print("\n特征重要性排序 (基于MSE增加量):")
    print(importance_df.to_string(index=False))
    print(f"\n基准 MSE: {baseline_mse:.6f}")

    # 绘制特征重要性图
    plot_feature_importance(
        importance_df,
        title="FNPG Feature Importance (Permutation)",
        save_path='/content/drive/MyDrive/logcompletion/figure/R1_9_feature_importance.pdf'
    )
except Exception as e:
    print(f"特征重要性分析出错: {e}")
    print("跳过此分析，继续执行...")

# ============================================================================
# R2-3: 逆变换工作流程
# ============================================================================
print("\n" + "="*70)
print("R2-3: 逆变换工作流程")
print("="*70)

# 初始化逆变换器
inverse_transformer = InverseTransformer()

# 尝试加载标准化参数
standard_data_path = '/content/drive/MyDrive/logcompletion/data/Teamdata/complete_data_for_PIModel/standard_data.csv'
try:
    inverse_transformer.load_standard_params(standard_data_path)
except Exception as e:
    print(f"加载标准化参数失败: {e}")
    print("从原始 CSV 数据计算标准化参数...")

    # 从原始 CSV 数据中计算均值和标准差
    # 输出特征（移除CALI）：RSHA, RMED, RDEP, SP
    output_features = ['RSHA', 'RMED', 'RDEP', 'SP']

    for feat_name in output_features:
        if feat_name in train_ori_set_2.columns:
            # 计算原始数据的均值和标准差
            feat_data = train_ori_set_2[feat_name].dropna()
            mean_val = feat_data.mean()
            std_val = feat_data.std()
            inverse_transformer.set_feature_stats(feat_name, mean_val, std_val)
            print(f"  {feat_name}: mean={mean_val:.4f}, std={std_val:.4f}")
        else:
            print(f"  警告: 特征 {feat_name} 不在 CSV 中")

    # 输入特征（如果需要）：GR, RHOB, NPHI, DTC
    input_features = ['GR', 'RHOB', 'NPHI', 'DTC']
    for feat_name in input_features:
        if feat_name in train_ori_set_2.columns:
            feat_data = train_ori_set_2[feat_name].dropna()
            mean_val = feat_data.mean()
            std_val = feat_data.std()
            inverse_transformer.set_feature_stats(feat_name, mean_val, std_val)
        else:
            print(f"  警告: 特征 {feat_name} 不在 CSV 中")

# 对预测结果进行反标准化演示
print("\n预测值反标准化示例:")
if predict is not None:
    # 获取标准化的预测值
    standardized_pred = predict.clone()

    # 执行反标准化
    try:
        # 确定预测结果的实际特征数量
        pred_n_features = standardized_pred.shape[1] if len(standardized_pred.shape) > 2 else standardized_pred.squeeze(0).shape[0]
        destandardized_pred = inverse_transformer.inverse_transform_batch(
            standardized_pred.squeeze(0),
            target_feature_names_GCRR[:pred_n_features]
        )

        # 报告变换前后的统计信息
        inverse_transformer.report_transform_stats(
            standardized_pred.squeeze(0),
            destandardized_pred,
            target_feature_names_GCRR[:pred_n_features]
        )
    except Exception as e:
        print(f"反标准化失败: {e}")

# ============================================================================
# R2-4: 统计显著性测试
# ============================================================================
print("\n" + "="*70)
print("R2-4: 统计显著性测试")
print("="*70)

# 计算每口井的评估指标
# 这里假设我们有多口井的数据
print("\n计算各井评估指标...")

# 对多口井分别进行推理和评估
try:
    # 选择要评估的井（测试集的两口井：15/9-15, 15/9-17）
    test_well_indices = [0, 1]  # 只使用前两口测试井

    all_predictions = []
    all_targets = []
    well_names = []

    print(f"对 {len(test_well_indices)} 口井进行推理...")

    for well_idx in test_well_indices:
        # 获取该井的输入和目标数据
        well_input = tensor_list_y[well_idx].clone()
        # 移除CALI通道：[:,2:,:] 跳过深度列(0)和CALI列(1)，只保留RSHA, RMED
        well_target = torch.cat((tensor_list_target[well_idx][:,2:,:].clone(),
                                 tensor_list_target_2[well_idx][:,1:3,:].clone()), dim=1)

        # 创建数据加载器
        well_dataset = my_dataset(well_input, well_target)
        well_loader = DataLoader(
            well_dataset,
            batch_size=2,
            num_workers=0,
            shuffle=False,
            drop_last=True,
            collate_fn=custom_collate
        )

        # 推理
        model.eval()
        well_preds = []
        with torch.no_grad():
            for batch in well_loader:
                batch.x = batch.x.view(-1, 4, 512)
                output = model(batch)
                # 移除CALI通道（索引0），只保留RSHA, RMED, RDEP, SP
                output = output[:, 1:, :]  # 从 (N, 5, 512) 变为 (N, 4, 512)
                well_preds.append(output.cpu())

        # 合并预测结果
        well_pred = torch.cat(well_preds, dim=0)
        well_target_aligned = well_target[:well_pred.shape[0]]

        all_predictions.append(well_pred)
        all_targets.append(well_target_aligned)
        well_names.append(f"Well_{well_idx}")

        print(f"  井 {well_idx}: {well_pred.shape[0]} 个样本")

    # 计算每口井的指标（包括样本级MSE）
    metrics_list = []
    sample_level_mse_list = []  # 新增：存储样本级MSE

    for i, (pred, target) in enumerate(zip(all_predictions, all_targets)):
        # 计算该井的指标
        pred_np = pred.numpy()
        target_np = target.cpu().numpy()  # 确保 target 在 CPU 上再转换为 numpy

        # 新增：计算每个样本（切片）的MSE
        n_samples = pred_np.shape[0]
        sample_mses = []
        for sample_idx in range(n_samples):
            sample_pred = pred_np[sample_idx].flatten()
            sample_target = target_np[sample_idx].flatten()
            sample_mse = np.mean((sample_pred - sample_target) ** 2)
            sample_mses.append({
                'Well_ID': i,
                'Sample_ID': sample_idx,
                'MSE': sample_mse
            })
        sample_level_mse_list.extend(sample_mses)

        # 展平数据计算整体指标
        pred_flat = pred_np.flatten()
        target_flat = target_np.flatten()

        mse = np.mean((pred_flat - target_flat) ** 2)
        rmse = np.sqrt(mse)
        mae = np.mean(np.abs(pred_flat - target_flat))

        ss_res = np.sum((target_flat - pred_flat) ** 2)
        ss_tot = np.sum((target_flat - np.mean(target_flat)) ** 2)
        r2 = 1 - (ss_res / ss_tot) if ss_tot > 0 else 0

        pearson_r, pearson_p = stats.pearsonr(pred_flat, target_flat)

        metrics_list.append({
            'Well_ID': i,
            'MSE': mse,
            'RMSE': rmse,
            'MAE': mae,
            'R2': r2,
            'Pearson_R': pearson_r,
            'Pearson_P': pearson_p,
            'N_Samples': pred.shape[0]
        })

    metrics_df = pd.DataFrame(metrics_list)
    sample_level_mse_df = pd.DataFrame(sample_level_mse_list)  # 新增：样本级MSE的DataFrame

    print(f"\n样本级MSE统计:")
    print(f"  总样本数: {len(sample_level_mse_df)}")
    print(f"  井0样本数: {len(sample_level_mse_df[sample_level_mse_df['Well_ID']==0])}")
    print(f"  井1样本数: {len(sample_level_mse_df[sample_level_mse_df['Well_ID']==1])}")

    # 生成统计显著性报告（传入样本级MSE数据）
    significance_summary = statistical_significance_report(
        metrics_df,
        sample_level_mse_df=sample_level_mse_df,  # 新增参数
        save_path='/content/drive/MyDrive/logcompletion/figure/R2_4_statistical_significance.pdf'
    )

except Exception as e:
    print(f"统计显著性测试出错: {e}")
    import traceback
    traceback.print_exc()

# ============================================================================
# 分析完成
# ============================================================================
print("\n" + "="*70)
print("所有分析完成!")
print("="*70)
print("\n已完成的分析项目:")
print("  ✓ R1-10: 相关性矩阵分析")
print("  ✓ R1-11: 训练/测试样本统计")
print("  ✓ R2-1:  计算效率指标")
print("  ✓ R1-9:  特征重要性分析")
print("  ✓ R2-3:  逆变换工作流程")
print("  ✓ R2-4:  统计显著性测试")
print("\n生成的图片保存在: /content/drive/MyDrive/logcompletion/figure/")
print("="*70)

